### PR TITLE
add ci job for eval_llama with mmlu task

### PR DESCRIPTION
**Pull request by helunwencser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #6344
* __->__ #6337
* #6336

Differential Revision: [D64565303](https://our.internmc.facebook.com/intern/diff/D64565303)

### CODE REVIEW

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64565303).

**Review by cccclai — APPROVED** [review]
Great to have more test coverage :)

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64565303).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64565303).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64565303).

**Pull request closed without merging**
