### PR TITLE
Increase memory allocated for inputs in case semi hosting is used.

### PR DESCRIPTION
**Pull request by freddan80**
Enable E2E MNV2 unit test

### CODE REVIEW

**Comment by freddan80** [comment]
Needs #5302 to pass CI

**Comment by freddan80** [comment]
On a second thought, it doesn't need #5302 to pass Github CI (just our intenal CI) :) 

The CI failures we see are unrelated to this PR.

**Review by digantdesai — APPROVED** [review]

**Comment by freddan80** [comment]
Rebased, just in case

**Comment by freddan80** [comment]
Ready to merge

**Pull request closed without merging**
