### PR TITLE
[RELEASE-ONLY] Set pytorch to 2.4

### PR DESCRIPTION
**Pull request by lucylq**
Set pytorch to 2.4
- github workflows
- CI

### CODE REVIEW

**Comment by kirklandsign** [comment]
merge to release/0.3 or main?

**Comment by lucylq** [comment]
> merge to release/0.3 or main?

ahh good catch - updated!

**Review by kirklandsign — APPROVED** [review]

**Comment by mergennachin** [comment]
- I added `ciflow/trunk` tag to run trunk jobs 
- Are you gonna modify `install_requirements.sh` as well to install latest torch rc candidates?

**Comment by lucylq** [comment]
> * I added `ciflow/trunk` tag to run trunk jobs
> * Are you gonna modify `install_requirements.sh` as well to install latest torch rc candidates? Could be a follow-up PR too.

It looks like 2.4 doesn't have a pip package yet, so may need to wait for that before modifying install_requirements.sh?
https://pypi.org/project/torch/2.4.0/

**Review by mergennachin — APPROVED** [review]

**Review by guangy10 — APPROVED** [review]

**Pull request merged**
