### PR TITLE
Exclude --gc-sections for llama2 example on MacOS

### LINKED ISSUE #3600: Llama example build failure on MacOS
When building the llama_main target on MacOS, build fails with the following error:

```
[100%] Linking CXX executable llama_main
ld: warning: -s is obsolete
ld: unknown options: --gc-sections
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [llama_main] Error 1
make[1]: *** [CMakeFiles/llama_main.dir/all] Error 2
```

In the top-level CMakeLists.txt, the --gc-sections flag is conditionally excluded when building for apple (https://github.com/GregoryComer/executorch/blob/c69861ddcee5705d37e7d47e2cccdeac741c71e8/CMakeLists.txt#L510). We may just need to do the same thing in the Llama example?

### PR DESCRIPTION
**Pull request by benkli01**
The flag '--gc-sections' seems to be unsupported on MacOS. The same resolution was applied here, it seems:
https://github.com/pytorch/executorch/blob/27d5329c627eb4396fe597de395400c08d88e354/CMakeLists.txt#L527

I run into the error from #3600 when I follow the [README.md here](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md#step-4-run-on-your-computer-to-validate).

Resolves #3600

### CODE REVIEW

**Comment by cccclai** [comment]
It seems working for me without this pr. Which MacOS version are you using?

**Comment by benkli01** [comment]
> It seems working for me without this pr. Which MacOS version are you using?

Strange, but I don't seem to be the only one with this issue (see linked isse). 
I'm using Sonoma 14.5 and clang version 15.0.0 (clang-1500.3.9.4).

**Comment by cccclai** [comment]
The commands on https://github.com/pytorch/executorch/pull/4160 works for me and I can build `llama_main` on mac. What is your repro command?

**Comment by benkli01** [comment]
Thanks @cccclai ! I just updated the description. I'm following the steps in the current [README.md here](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md#step-4-run-on-your-computer-to-validate) and is just verified I can still reproduce the error.

The main differences to the commands linked by you are that I'm using XNNPACK and release mode.

**Comment by cccclai** [comment]
Thanks, this change lgtm - looks like you'd need to sign CLA. They can be done following https://github.com/pytorch/executorch/pull/4156/checks?check_run_id=27080230335

**Review by cccclai — APPROVED** [review]

**Comment by guangy10** [comment]
@benkli01 fyi, the fix is merged in #4473

**Comment by benkli01** [comment]
Fixed in https://github.com/pytorch/executorch/pull/4473.

**Pull request closed without merging**
