### PR TITLE
add Qualcomm SA8295 support

### LINKED ISSUE #1176: Support more Qualcomm SoCs
Support more Qualcomm SoCs when use Qualcomm AI Engine Direc.

### PR DESCRIPTION
**Pull request by tianxf99**
### Summary
Attempting to add Qualcomm SA8295 support. Noticed a prior attempt one year ago (#1196). If anyone is currently working on this, I'd be happy to collaborate! :D

### Fixes
Fixes #1176

### CODE REVIEW

**Comment by cccclai** [comment]
@chiwwang hey can you help with reviewing?

**Review by shewu-quic — COMMENTED** [review]
Thanks for your effort. 
Could you help to rebase it?

**Review by chiwwang — APPROVED** [review]
Looks great!
~~Maybe a rebase can make the merge process easier but~~ this PR looks good for me.
[update] oh, never mind. I saw it is rebased!

**Review by cccclai — APPROVED** [review]
Thanks for adding support for more SoCs!

**Comment by cccclai** [comment]
Hi @tianxf99, thank you for contributing! Just curious, what is your use case?

**Comment by ali-khosh** [comment]
> ### Summary
> Attempting to add Qualcomm SA8295 support. Noticed a prior attempt one year ago (#1196). If anyone is currently working on this, I'd be happy to collaborate! :D
> 
> ### Fixes
> Fixes #1176

Hey @tianxf99 glad to see this work. I'm the PM with the ExecuTorch team. Would love to know if you can share some context around why this PR matters for you and what you're trying to accomplish.

**Pull request merged**
