### PR TITLE
Update executorch-arm-delegate-tutorial.md with CS320 FVP

### PR DESCRIPTION
**Pull request by varunchariArm**
Summary:
Updating the Arm delegate documentation to support Crostone 320 FVP and additional options in `run.sh` script

### CODE REVIEW

**Comment by digantdesai** [comment]
Looks good at a high level, lets address some of these comments.

**Comment by digantdesai** [comment]
Also @varunchariArm  - `The author does not have a valid CLA on file.`!

**Comment by varunchariArm** [comment]
> Also @varunchariArm - `The author does not have a valid CLA on file.`!

Submitted request to get CLA.

**Comment by digantdesai** [comment]
FYI can't merge until CLA goes through

**Comment by varunchariArm** [comment]
HI Digant,
Seems like CLA is signed, can you please review the PR?
Thanks

**Pull request merged**
