### PR TITLE
Qualcomm AI Engine Direct - fix conv2d to meet QNN constraint

### PR DESCRIPTION
**Pull request by haowhsu-quic**
Summary:
- fix breakage of conv2d without bias in newer QNN SDK (>=2.24)
- add test cases for conv2d
- refactor some keywords

### CODE REVIEW

**Comment by haowhsu-quic** [comment]
Hi @cccclai, this is a fix for breakage introduce in recent QNN version. It relates to https://github.com/pytorch/executorch/issues/4517 about static_llama conv2d validation failure.
Thank you.

**Review by cccclai — APPROVED** [review]
Thanks for the fix!

**Comment by haowhsu-quic** [comment]
Hi, I wonder if we could have this merged to use newer QNN versions, thank you!

**Comment by cccclai** [comment]
Hey sorry I miss it - could you rebase and I will merge it tomorrow?

**Comment by yuanmenglong886** [comment]
Does this change also apply to the PyTorch version? Not the Executorch version?

**Comment by cccclai** [comment]
> Does this change also apply to the PyTorch version? Not the Executorch version?

Can you elaborate a bit more for the question? I think before this PR, con2d fails to lower to qnn and now it can be lower.

**Pull request merged**
