### PR TITLE
enable parallel prefill

### PR DESCRIPTION
**Pull request by kimishpatel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #4068
* #4067
* #4066
* #4065
* #4064

CHanges include
- Model export changes to allow indexing into freqcis
- xnnpack delegate change to partition with dynamic shape
- runner change to do perfill in single step

Differential Revision: [D58874164](https://our.internmc.facebook.com/intern/diff/D58874164/)

### CODE REVIEW

**Review by larryliu0820 — APPROVED** [review]

**Comment by dz217711** [comment]
Hi @kimishpatel,

Thank you for the excellent work. I tried the patch today using the following command:
```bash
python -m examples.models.llama2.export_llama --checkpoint ./stories110M/stories110M.pt -p ./stories110M/params.json -o ptes -n stories110M_parallel_prefill -kv -X
```

However, I encountered an error when attempting to generate the PTE with dynamic shape enabled. I have attached the traceback below. Could you please help me identify what went wrong?

Best regards

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/executorch/examples/models/llama2/export_llama.py", line 31, in <module>
    main()  # pragma: no cover
  File "/workspace/executorch/examples/models/llama2/export_llama.py", line 27, in main
    export_llama(modelname, args)
  File "/workspace/executorch/examples/models/llama2/export_llama_lib.py", line 316, in export_llama
    builder = _export_llama(modelname, args)
  File "/workspace/executorch/examples/models/llama2/export_llama_lib.py", line 480, in _export_llama
    backend = builder_exported_to_edge.to_backend(partitioners)
  File "/workspace/executorch/examples/models/llama2/builder.py", line 360, in to_backend
    self.edge_manager = self.edge_manager.to_backend(partitioner)
  File "/workspace/executorch/exir/program/_program.py", line 1166, in to_backend
    new_edge_programs[name] = to_backend(program, partitioner)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/workspace/executorch/exir/backend/backend_api.py", line 384, in _
    tagged_graph_module = _partition_and_lower(
  File "/workspace/executorch/exir/backend/backend_api.py", line 316, in _partition_and_lower
    res = ExportPass()(tagged_graph_module)
  File "/workspace/executorch/third-party/pytorch/torch/fx/passes/infra/pass_base.py", line 40, in __call__
    res = self.call(graph_module)
  File "/workspace/executorch/exir/pass_base.py", line 571, in call
    result = self.call_submodule(graph_module, tuple(inputs))
  File "/workspace/executorch/exir/pass_base.py", line 657, in call_submodule
    res = super().call_submodule(graph_module, inputs)
  File "/workspace/executorch/exir/pass_base.py", line 534, in call_submodule
    interpreter.run(*inputs_data)
  File "/workspace/executorch/third-party/pytorch/torch/fx/interpreter.py", line 145, in run
    self.env[node] = self.run_node(node)
  File "/workspace/executorch/exir/pass_base.py", line 374, in run_node
    return super().run_node(n)
  File "/workspace/executorch/third-party/pytorch/torch/fx/interpreter.py", line 202, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/workspace/executorch/exir/pass_base.py", line 606, in call_function
    return self.callback.call_operator(
  File "/workspace/executorch/exir/pass_base.py", line 465, in call_operator
    return self._fx("call_function", op, args, kwargs, meta)
  File "/workspace/executorch/exir/pass_base.py", line 396, in _fx
    res_data = getattr(self.interpreter, kind)(target, args_data, kwargs_data)
  File "/workspace/executorch/third-party/pytorch/torch/fx/interpreter.py", line 274, in call_function
    return target(*args, **kwargs)
  File "/workspace/executorch/exir/dialects/edge/_ops.py", line 333, in __call__
    return self._op(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_subclasses/fake_tensor.py", line 896, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_subclasses/fake_tensor.py", line 1241, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_subclasses/fake_tensor.py", line 974, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_subclasses/fake_tensor.py", line 1458, in _dispatch_impl
    r = func(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_decomp/decompositions.py", line 756, in slice_forward
    elif end_val > sizes[dim]:
  File "/workspace/executorch/third-party/pytorch/torch/__init__.py", line 374, in __bool__
    return self.node.bool_()
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/sym_node.py", line 432, in bool_
    return self.guard_bool("", 0)
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/sym_node.py", line 374, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/recording.py", line 255, in wrapper
    return event.run(self)
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/recording.py", line 156, in run
    return self.f(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/symbolic_shapes.py", line 4138, in evaluate_expr
    raise self._make_data_dependent_error(
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression u375 + 4 > 128 (unhinted: s0 + u375 > 128).  (Size-like symbols: none)

Potential framework code culprit (scroll up for full backtrace):
  File "/workspace/executorch/third-party/pytorch/torch/_decomp/decompositions.py", line 756, in slice_forward
    elif end_val > sizes[dim]:

For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u375"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing


While executing %aten_slice_copy_tensor : [num_users=12] = call_function[target=executorch.exir.dialects.edge._ops.aten.slice_copy.Tensor](args = (%arg111_1, 0, %_local_scalar_dense, %add_2), kwargs = {})
Original traceback:
  File "/workspace/executorch/examples/models/llama2/llama_transformer.py", line 522, in forward
    freqs_cos = self.freqs_cos.narrow(0, input_pos_item, seqlen)
```

**Comment by DzAvril** [comment]
Hi @kimishpatel,

Thank you for the excellent work. I tried the patch today using the following command:
```bash
python -m examples.models.llama2.export_llama --checkpoint ./stories110M/stories110M.pt -p ./stories110M/params.json -o ptes -n stories110M_parallel_prefill -kv -X
```

However, I encountered an error when attempting to generate the PTE with dynamic shape enabled. I have attached the traceback below. Could you please help me identify what went wrong?

Best regards

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/executorch/examples/models/llama2/export_llama.py", line 31, in <module>
    main()  # pragma: no cover
  File "/workspace/executorch/examples/models/llama2/export_llama.py", line 27, in main
    export_llama(modelname, args)
  File "/workspace/executorch/examples/models/llama2/export_llama_lib.py", line 316, in export_llama
    builder = _export_llama(modelname, args)
  File "/workspace/executorch/examples/models/llama2/export_llama_lib.py", line 480, in _export_llama
    backend = builder_exported_to_edge.to_backend(partitioners)
  File "/workspace/executorch/examples/models/llama2/builder.py", line 360, in to_backend
    self.edge_manager = self.edge_manager.to_backend(partitioner)
  File "/workspace/executorch/exir/program/_program.py", line 1166, in to_backend
    new_edge_programs[name] = to_backend(program, partitioner)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/workspace/executorch/exir/backend/backend_api.py", line 384, in _
    tagged_graph_module = _partition_and_lower(
  File "/workspace/executorch/exir/backend/backend_api.py", line 316, in _partition_and_lower
    res = ExportPass()(tagged_graph_module)
  File "/workspace/executorch/third-party/pytorch/torch/fx/passes/infra/pass_base.py", line 40, in __call__
    res = self.call(graph_module)
  File "/workspace/executorch/exir/pass_base.py", line 571, in call
    result = self.call_submodule(graph_module, tuple(inputs))
  File "/workspace/executorch/exir/pass_base.py", line 657, in call_submodule
    res = super().call_submodule(graph_module, inputs)
  File "/workspace/executorch/exir/pass_base.py", line 534, in call_submodule
    interpreter.run(*inputs_data)
  File "/workspace/executorch/third-party/pytorch/torch/fx/interpreter.py", line 145, in run
    self.env[node] = self.run_node(node)
  File "/workspace/executorch/exir/pass_base.py", line 374, in run_node
    return super().run_node(n)
  File "/workspace/executorch/third-party/pytorch/torch/fx/interpreter.py", line 202, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/workspace/executorch/exir/pass_base.py", line 606, in call_function
    return self.callback.call_operator(
  File "/workspace/executorch/exir/pass_base.py", line 465, in call_operator
    return self._fx("call_function", op, args, kwargs, meta)
  File "/workspace/executorch/exir/pass_base.py", line 396, in _fx
    res_data = getattr(self.interpreter, kind)(target, args_data, kwargs_data)
  File "/workspace/executorch/third-party/pytorch/torch/fx/interpreter.py", line 274, in call_function
    return target(*args, **kwargs)
  File "/workspace/executorch/exir/dialects/edge/_ops.py", line 333, in __call__
    return self._op(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_subclasses/fake_tensor.py", line 896, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_subclasses/fake_tensor.py", line 1241, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_subclasses/fake_tensor.py", line 974, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_subclasses/fake_tensor.py", line 1458, in _dispatch_impl
    r = func(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/_decomp/decompositions.py", line 756, in slice_forward
    elif end_val > sizes[dim]:
  File "/workspace/executorch/third-party/pytorch/torch/__init__.py", line 374, in __bool__
    return self.node.bool_()
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/sym_node.py", line 432, in bool_
    return self.guard_bool("", 0)
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/sym_node.py", line 374, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/recording.py", line 255, in wrapper
    return event.run(self)
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/recording.py", line 156, in run
    return self.f(*args, **kwargs)
  File "/workspace/executorch/third-party/pytorch/torch/fx/experimental/symbolic_shapes.py", line 4138, in evaluate_expr
    raise self._make_data_dependent_error(
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression u375 + 4 > 128 (unhinted: s0 + u375 > 128).  (Size-like symbols: none)

Potential framework code culprit (scroll up for full backtrace):
  File "/workspace/executorch/third-party/pytorch/torch/_decomp/decompositions.py", line 756, in slice_forward
    elif end_val > sizes[dim]:

For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u375"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing


While executing %aten_slice_copy_tensor : [num_users=12] = call_function[target=executorch.exir.dialects.edge._ops.aten.slice_copy.Tensor](args = (%arg111_1, 0, %_local_scalar_dense, %add_2), kwargs = {})
Original traceback:
  File "/workspace/executorch/examples/models/llama2/llama_transformer.py", line 522, in forward
    freqs_cos = self.freqs_cos.narrow(0, input_pos_item, seqlen)
```

**Comment by kimishpatel** [comment]
I will try to repro this

**Comment by DzAvril** [comment]
> I will try to repro this

Thank you for your response. I updated to the latest commit, and the issue has been resolved.

**Comment by kimishpatel** [comment]
> > I will try to repro this
> 
> Thank you for your response. I updated to the latest commit, and the issue has been resolved.

Awesome

**Pull request closed without merging**
