### PR TITLE
[llava][4/N] Allow llama_transformer take embedding as optional argument

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #4259
* #4256
* __->__ #4257
* #4242
* #4241

Summary: Llava run token embedding separately and combine that with
image embeddings as input to text transformer. This PR adds support for
that.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D59759977](https://our.internmc.facebook.com/intern/diff/D59759977)

### CODE REVIEW

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759977).

**Review by tarun292 — APPROVED** [review]

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759977).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759977).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759977).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759977).

**Pull request closed without merging**
