### PR TITLE
export phi-3-mini-wrapper

### PR DESCRIPTION
**Pull request by helunwencser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #4478
* #4491
* #4490
Differential Revision: [D60483506](https://our.internmc.facebook.com/intern/diff/D60483506)

### CODE REVIEW

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60483506).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60483506).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60483506).

**Review by iseeyuan — APPROVED** [review]
LGTM

**Pull request closed without merging**
