### PR TITLE
Port Arm backend op unittests: conv op + other ops

### PR DESCRIPTION
**Pull request by freddan80**
Ported unit tests with combined ops.

* Removed random seeds
* Removed corresponing legacy test cases

### CODE REVIEW

**Review by digantdesai — APPROVED** [review]
LGTM

**Comment by freddan80** [comment]
CI failure is related to this PR. We've move around the logger and I missed to update it. Will push fix tomorrow.

**Comment by freddan80** [comment]
These CI failures are unrelated to the PR

**Comment by digantdesai** [comment]
Rebase please?

**Review by mergennachin — APPROVED** [review]

**Comment by digantdesai** [comment]
Please rebase on top of the other one? executorch/backends/arm/test/test_models.py might have a conflict.

**Comment by freddan80** [comment]
Will do

**Pull request closed without merging**
