### PR TITLE
Pick pybind

### PR DESCRIPTION
**Pull request by larryliu0820**
Picking

https://github.com/pytorch/executorch/pull/5571
#5915
#5961
#5965
#6102
#6108
#6063

### CODE REVIEW

**Review by jackzhxng — COMMENTED** [review]
Deferring to @dbort

**Review by dbort — APPROVED** [review]
Looks good; it's what I remember seeing in all of the original commits

**Review by dbort — CHANGES_REQUESTED** [review]
Oh though I just saw that the linux unittest job crashed while running pybind tests, which is pretty suspicious:

https://github.com/pytorch/executorch/actions/runs/11285226831/job/31387667063?pr=6151#step:12:6679
```
_________________ extension/pybindings/test/test_pybindings.py _________________
[gw6] linux -- Python 3.10.15 /opt/conda/envs/py_3.10/bin/python
worker 'gw6' crashed while running 'extension/pybindings/test/test_pybindings.py::PybindingsTest::test'
```

This might be because https://github.com/pytorch/executorch/pull/6114 still hasn't been merged? The stack trace shows that the crash happened at "make_test.py, line 293 in test_constant_output_not_memory_planned"

EDIT: I landed #6114, and @larryliu0820 rebased this PR on top of it

**Review by dbort — APPROVED** [review]

**Comment by dbort** [comment]
Crashing again 😕 though in a different test this time

https://github.com/pytorch/executorch/actions/runs/11286510296/job/31391000961?pr=6151#step:12:6678
```
make_test.py", line 360 in test_bad_name
```

**Comment by larryliu0820** [comment]
> Crashing again 😕 though in a different test this time
> 
> https://github.com/pytorch/executorch/actions/runs/11286510296/job/31391000961?pr=6151#step:12:6678
> 
> ```
> make_test.py", line 360 in test_bad_name
> ```

yeah fixed

**Pull request merged**
