### PR TITLE
Cut dependencies and clean up Arm backend unit tester

### PR DESCRIPTION
**Pull request by freddan80**

### CODE REVIEW

**Comment by freddan80** [comment]
None of the CI issues are related to my changes. AFAIK.

**Comment by freddan80** [comment]
@digantdesai The CI fails aren't related to this PR. When I try to re-run the CI. the failing jobs are not triggered. How do I proceed?

**Review by digantdesai — APPROVED** [review]
LGTM

**Review by mergennachin — APPROVED** [review]

**Comment by digantdesai** [comment]
Can you rebase please?

**Comment by freddan80** [comment]
Done. Failing CI jobs unrelated to this change.

**Comment by freddan80** [comment]
Is this stuck on something that I have missed?

**Pull request closed without merging**
