### PR TITLE
resolve_buck.py: Add an entry for darwin-x86_64

### PR DESCRIPTION
**Pull request by dbort**
Version hash reported by
https://github.com/facebook/buck2/releases/download/2024-02-15/buck2-x86_64-apple-darwin.zst

### CODE REVIEW

**Comment by dbort** [comment]
I'm away from my work machine til next week so I won't be able to land this myself until then, so please clone/commandeer this PR if you think it'll be useful.

**Review by GregoryComer — APPROVED** [review]

**Comment by GregoryComer** [comment]
Thanks for grabbing the version hash.

**Comment by GregoryComer** [comment]
Trying again, since it seems like it didn't work. Maybe because I trigged the cherry-pick before the bot registered that it landed?

@pytorchbot cherry-pick --onto release/0.2 -c critical

**Pull request closed without merging**
