### PR TITLE
Update landing page to include Llama (#6218)

### PR DESCRIPTION
**Pull request by mergennachin**
Summary:

We should promote llama page more and demote the LLM Manual.

allow-large-files

Differential Revision: D64375318

### CODE REVIEW

**Review by kirklandsign — COMMENTED** [review]
So we will use https://docs-preview.pytorch.org/pytorch/executorch/6231/llm/llama.html instead of https://docs-preview.pytorch.org/pytorch/executorch/6231/llm/getting-started.html?

**Comment by mergennachin** [comment]
@kirklandsign both exist, just making sure llama2/readme.md is reachable from the website, currently it is not reachable at all.

the getting-started page is still there, but just demoted to fourth bullet in the TOC

**Review by jackzhxng — APPROVED** [review]

**Pull request closed without merging**
