### PR TITLE
Regression fixes and tidyup for Arm backend

### PR DESCRIPTION
**Pull request by robell**
Fixes for a few things:

- Move C++ std to 17 to enable changes for #1733 on Arm builds
- fix after #2307 regressed save_pte_program on aot_arm_compiler
- add aot_arm_compiler support for examples/models (they don't all compile but can be consumed)
- Move the Vela pin in anticipation of MNV2 tosa fixes in #2371

### CODE REVIEW

**Review by digantdesai — APPROVED** [review]
sweet, looks great!

**Comment by digantdesai** [comment]
>  Pull Request cannot be merged
Rebase please?

**Comment by digantdesai** [comment]
sigh, rebase please? Thanks. Something is wrong. I might have to commandeer it.

**Comment by robell** [comment]
> sigh, rebase please? Thanks. Something is wrong. I might have to commandeer it.

sorry was out, done now, hopefully this works.

**Pull request closed without merging**
