### PR TITLE
add mobilebert quant (#95)

### PR DESCRIPTION
**Pull request by haowhsu-quic**
[Add mobilebert quantization example]
- reduce_dynamic_range: change the float.min to -255.0 for mobilebert
- convert_addmm_back_to_linear: To handle missing quantization tag for addmm op after decomposing. (to_edge)
- convert_bmm_to_matmul: To handle missing quantization tag for bmm op after decomposing. (to_edge)
- add 16bit quantization config.
- fallback embedding op (Due to some problems in Qnn runtime) modify fold_qdq for multi output.
- document fix

Note that this quantized mobilebert need to be run in QNN 2.12 for stability, and other examples have been tested in QNN 2.12

---------

Co-authored-by: shewu-quic <quic_shewu@quicinc.com>
Co-authored-by: chunit-quic <quic_chunit@quicinc.com>

### CODE REVIEW

**Comment by kimishpatel** [comment]
Strange, that this got auto closed. Apologies. Lets open it again.

**Comment by kimishpatel** [comment]
@shewu-quic please submit the PR again. I am not sure how to open this again.

**Comment by shewu-quic** [comment]
> @shewu-quic please submit the PR again. I am not sure how to open this again.

ok. got it. Due to legal constraint, we will do as soon as possible.
Thanks.

**Comment by chiwwang** [comment]
A context: because this repo is public now, we have a slightly different path to raise new PR.
Let's wait until next Tueday. If they cannot handle this in time, I will think about alternatives.

**Comment by chiwwang** [comment]
Re-raise on behavior of @shewu-quic  here:
https://github.com/pytorch/executorch/pull/1043

**Pull request closed without merging**
