### PR TITLE
Move to TOSA v0.80.1

### PR DESCRIPTION
**Pull request by mansnils**
Arm backend use TOSA v0.80.1.

### CODE REVIEW

**Comment by mansnils** [comment]
`@pytorchbot label "topic: not user facing"`

**Comment by mansnils** [comment]
pytorchbot label "topic: not user facing"

**Review by freddan80 — APPROVED** [review]

**Comment by mansnils** [comment]
> This change needs rebuilt docker file. Probably also a rebase.
> 
> @mansnils Will you rebase this change pls?

Done

**Pull request merged**
