### PR TITLE
Implement dumping operator distribution for TOSA graph

### PR DESCRIPTION
**Pull request by Erik-Lundell**
When dumping the operator distribution after ArmTeste.partition, operators are counted both in the Edge IR and the TOSA graph. The complete output looks something like:
"operators: {op1: 3, op2: 5....}
TOSA operators: {op1: 2, op2: 3}"

Change-Id: I946e8487ad185d9994049ddcdcf7b08153c2597b

### CODE REVIEW

**Comment by digantdesai** [comment]
Nit: perhaps put example output in the commit message or PR summary?

**Review by digantdesai — APPROVED** [review]

**Comment by Erik-Lundell** [comment]
> Nit: perhaps put example output in the commit message or PR summary?

Updated the PR summary for both comments :)

**Comment by dbort** [comment]
@Erik-Lundell @digantdesai The `pull / unittest-arm (buck2) / linux-job` and `trunk / test-arm-reference-delegation / linux-job` jobs started failing in trunk ([dashboard](https://hud.pytorch.org/hud/pytorch/executorch/main)) after this PR merged.

Example failure ([job](https://github.com/pytorch/executorch/actions/runs/10724733722/job/29741046254#step:12:14429)):
```
FAILED ../../dev/misc/test_debug_feats.py::test_fail_dump_tosa_ops - SystemExit: 2
= 1 failed, 434 passed, 73 skipped, 134 xfailed, 169 warnings in 467.22s (0:07:47) =
```

**Comment by dbort** [comment]
@Erik-Lundell I've reverted this PR in https://github.com/pytorch/executorch/pull/5131

**Pull request merged**
