### PR TITLE
Qualcomm AI Engine Direct Backend

### PR DESCRIPTION
**Pull request by haowhsu-quic**
Hi there,

This commit adds QNN backend. Please check setup.md and README under `backends/qnn` for more details.

We add pybind dependency at the top level, because we guess you might need it in the near future. If it's not the case, please feel free to tell us. We'll move it under `backends/qnn`.

Below is some SoC model mapping:

- `SM8550` -> `Snapdragon 8 Gen 2`
- `SM8475` -> `Snapdragon 8 Gen 1+`
- `SM8450` -> `Snapdragon 8 Gen 1`

Please feel free to contact us if you find any problem.

---------

Co-authored-by: shewu-quic <quic_shewu@quicinc.com>
Co-authored-by: chunit-quic <quic_chunit@quicinc.com>
Co-authored-by: chiwwang <quic_chiwwang@quicinc.com>
Co-authored-by: harshs-qti <quic_harshs@quicinc.com>

### CODE REVIEW

**Review by mergennachin — COMMENTED** [review]
Could you move 

backends/qnn/examples to top-level examples/qualcomm instead?

Still reviewing...

**Review by cccclai — COMMENTED** [review]
This pr looks great! All codes are well organized and easy to read. Thank you! Just left some comments on the naming probably due to rebase.

**Review by kimishpatel — COMMENTED** [review]
some early comments. still reviewing

**Review by kimishpatel — CHANGES_REQUESTED** [review]
Have mostly reviewed ahead of time delegation stuff. 

Not yet reviewed:
- quantizer
- runtime stuff
- any of the examples

Havent tried to reproduce anything following these steps. I will try to unblock you guys on review and in parallel repro your stuff. 

For the large this looks quite good. I have tagged comments with `nit` and `comment`. nit ones are upto you to address. The comments which are tagged with neight of the two, I would like you take a look and address. Unfortunately, in the previous round, I didnt tag any of my comments.

**Review by kimishpatel — CHANGES_REQUESTED** [review]
last round.

highlights:
- Please take a look at comments in the test folder
- Generally in ExecuTorch all the folder with code have test filder that test code in that folder. This is not something to be addressed now and maybe some cannot be tested since it is device specific, but just pointing this out.
- All the in runtime/backends folder seems specific implementation that potentially live in a different place. But this likely will need larger discussion in terms of how we structure the code and what code should live in ExecuTorch repo. Maybe we conclude that all of this lives in ExecuTorch repo, but we need to discuss this.

Otherwise, this looks pretty good. Lets aim to land this in a couple of days.

**Review by mergennachin — APPROVED** [review]
Thanks for making the suggested changes.

One last minor request.

Would you mind moving `examples/backends/qualcomm` to just `examples/qualcomm`?

And move all the relevant scripts (e.g. export_example.py) to `examples/qualcomm/scripts/...`?

Also, keep the `executor_runner` in `examples/qualcomm/executor_runner/` as is.

Currently we are doing refactoring within in our examples folder, and it'd be great if qualcomm had similar structure as us.

Otherwise, LGTM

cc Will let @kimishpatel take a one last look.

**Review by kimishpatel — APPROVED** [review]
Looks good. I will try to land this by importing it internally.

**Review by guangy10 — COMMENTED** [review]
The demos code structure in the `examples/` looks good to me!

**Pull request closed without merging**
