### PR TITLE
[emitter] hash constant buffer to improve deduplication performance

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #1185

Summary:

Currently for each constant tensor we need to compare its buffer with
all the emitted buffer before to see if there's a duplicate. This is bad
especially if we have more than one ExecutionPlan in the program. This
PR introduces a map from the hash value to buffer index and hopefully
can largely reduce the deduplication time.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D51182655](https://our.internmc.facebook.com/intern/diff/D51182655)

### CODE REVIEW

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51182655).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51182655).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51182655).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51182655).

**Comment by JacobSzwejbka** [comment]
Nice!

FWIW we don't attempt to deduplicate within an execution plan, so the deduplication logic only runs if theres > 1 entry point. It also hopefully wasn't too bad before because we would consider metadata first and then for the vast majority of non duplicates even if the metadata matched you would exit out on the first data entry because floats rarely match exactly. If you had a ton of reused weights though this should be much faster though.

**Comment by JacobSzwejbka** [comment]
Nice!

**Review by JacobSzwejbka — APPROVED** [review]

**Comment by larryliu0820** [comment]
@JacobSzwejbka yeah I realized this change makes more sense for the scenario where we have more than 1 entry points. For single entry point I realized during debugging that mv3 model has tensors with duplicate values so hopefully that helps there.

**Pull request closed without merging**
