### PR TITLE
[MPS] Add index.Tensor and aten.logical_not

### PR DESCRIPTION
**Pull request by DenisVieriu97**
Add missing llama ops for MPS delegate:
- `index.Tensor` 
- `logical_not`

`index.put` works correctly for generating 1 token, but gives incorrect results on 2nd token. This remains disabled. 

Summary of changes:
- Adds missing llama2 ops
- Adds support for launching Metal kernels instead of MPSGraph ops (if MPSGraph doesn't have the support)

cc @cccclai , @shoumikhin

### CODE REVIEW

**Review by cccclai — APPROVED** [review]

**Comment by cccclai** [comment]
Thank you! The logical op is actually from decomposing sdpa - if the sdpa is not ready yet, maybe can use the simpler version https://github.com/pytorch/executorch/pull/3165 which has fewer ops than the decomposing `F.scaled_dot_product_attention`

**Comment by DenisVieriu97** [comment]
`Apple / test-demo-ios / macos-job (pull_request)` is failing because it uses the prebuilt `mpsdelegate` static lib stored in AWS (`https://ossci-ios.s3.amazonaws.com/executorch/`, `  "mps_backend": ["sha256": "97db0fd2b458ff4dae3f4e927d417b4ce88ef3bd4114759abe8372a05bac84ad"]` which doesn't match anymore with the runtime changes made in this PR. This PR is using the new AOT changes but the older runtime,  which are not compatible anymore. I've checked locally, and `Apple / test-demo-ios / macos-job` passes with the new runtime.
Any ideas how to fix this ? (cc @cccclai , @shoumikhin )

**Comment by DenisVieriu97** [comment]
> Thank you! The logical op is actually from decomposing sdpa - if the sdpa is not ready yet, maybe can use the simpler version #3165 which has fewer ops than the decomposing `F.scaled_dot_product_attention`

Thank you @cccclai . I'll take a look and create a new PR for those changes

**Comment by cccclai** [comment]
> > Thank you! The logical op is actually from decomposing sdpa - if the sdpa is not ready yet, maybe can use the simpler version #3165 which has fewer ops than the decomposing `F.scaled_dot_product_attention`
> 
> Thank you @cccclai . I'll take a look and create a new PR for those changes

oh sorry pointed to a wrong pr...should be this one https://github.com/pytorch/executorch/pull/3037. Regarding the test failure, probably @shoumikhin knows more. Will ping him tomorrow

**Pull request closed without merging**
