### PR TITLE
Add max_pool2d op to Arm backend

### PR DESCRIPTION
**Pull request by AdrianLundell**
- Adds node visitor and unittests
- Adds remove_getitem_op pass to convert (maxpool_get inidices + getitem) -> maxpool2d op

### CODE REVIEW

**Comment by digantdesai** [comment]
@AdrianLundell please sign the CLA, can't merge until then

**Comment by digantdesai** [comment]
Rebase?

**Comment by digantdesai** [comment]
If its in WIP, make it a Draft?

**Comment by digantdesai** [comment]
@AdrianLundell  - updated your permissions so hopefully the GH CI should rerun automatically when you push next time.

**Comment by zingo** [comment]
This is not WIP :)

**Comment by AdrianLundell** [comment]
Same tests are currently failing on main as well

**Comment by digantdesai** [comment]
@AdrianLundell  did you get an invite to join ExecuTorch repo? If you accept and join, you can run the CI and also merge the PRs :)

**Review by freddan80 — APPROVED** [review]

**Comment by AdrianLundell** [comment]
**Unrelated failures:**
-`
Segmentation fault      (core dumped) ./${CMAKE_OUTPUT_DIR}/executor_runner --model_path "./composite_model.pte"
Error: Process completed with exit code 1: 
` https://github.com/pytorch/executorch/actions/runs/11704081247/job/32595766387?pr=6285#step:12:7155

 -`RuntimeError: Command docker exec -t 2b0b828c480d4160eb41bea1294475db4d8decd34ee7b5c396d02d3f6c07b4ff /exec failed with exit code 139
Error: Process completed with exit code 1: `https://github.com/pytorch/executorch/actions/runs/11704081247/job/32595765663?pr=6285#step:12:6701



**Unclear if related:**
-`This Pull Request has changes that have not been imported to the Diff, please import the Pull Request:` https://github.com/pytorch/executorch/pull/6285/checks?check_run_id=32595759126

**Pull request merged**
