### PR TITLE
[llava][1/N] Take dynamic shape as an argument to LLMEdgeManager and

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #4259
* #4256
* #4257
* #4242
* __->__ #4241

remove unnecessary dynamic shape

Summary: As titled.

If we don't have `use_kv_cache` enabled, or we have
`enable_dynamic_shape`, the input token dimension is dynamic. With
`enable_dynamic_shape` enabled, we don't need to set dynamic shape for
input_pos since it will always be a scalar tensor.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D59759976](https://our.internmc.facebook.com/intern/diff/D59759976)

### CODE REVIEW

**Review by kimishpatel — APPROVED** [review]

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759976).

**Review by tarun292 — APPROVED** [review]

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759976).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759976).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759976).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759976).

**Pull request closed without merging**
