### PR TITLE
Polish CoreML Llama Doc

### PR DESCRIPTION
**Pull request by YifanShenSZ**
Document
* The export python script arguments to export llama for coreml
* The cmake argument to compile Mac runner with coreml backend

### CODE REVIEW

**Comment by YifanShenSZ** [comment]
@cccclai @cymbalrush

**Review by cccclai — APPROVED** [review]

**Comment by cccclai** [comment]
Actually do you mind seperating the doc change and the code change? doc change is easier to cherry pick while code change may take some time

**Comment by YifanShenSZ** [comment]
Sure, this PR now focuses only on doc update, to be cherry picked for beta release

Script clean up now stands alone in https://github.com/pytorch/executorch/pull/5762, and don't have to be cherry picked

**Pull request closed without merging**
