### PR TITLE
[ET-VK] Add third-party dependencies required for Vulkan Delegate

### PR DESCRIPTION
**Pull request by SS-JIA**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #2161

## Context

Splitting up https://github.com/pytorch/executorch/pull/2159 into different diffs, since the BUCK files will need some configerator changes to be landed first in order to set up correct OSS <-> internal aliases.

This PR simply adds the third party dependencies required to build the Vulkan delegate into ExecuTorch. The dependencies are:

* https://github.com/KhronosGroup/Vulkan-Headers @ `v1.3.210` - MIT License / Apache 2.0 License
* https://github.com/zeux/volk @ `1.3.250` - MIT License
* https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator  @ `v3.0.1` - MIT License

These are added under `executorch/backends/vulkan/third-party`.

These dependencies should be safe to add to ExecuTorch:

1. Licenses are compatible
2. Only used in Vulkan delegate - does not cause any build size increases for the rest of ExecuTorch
3. Repositories are fairly small; should not increase repo cloning time by much

Differential Revision: [D54318420](https://our.internmc.facebook.com/intern/diff/D54318420)

### CODE REVIEW

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54318420).

**Comment by mcr229** [comment]
hmm i have some commits failing on this: 
```
pull / unittest / macos (buck2) / macos-job (pull_request)
```  

too, executorch_hud looked cleaning, so I don't understand why its failing

**Review by cbilgin — APPROVED** [review]
These libs are already in use with LI and does not need further review. Good with the deps, thank you Stephen.

**Comment by SS-JIA** [comment]
@mcr229 could be a transient error. If you re-run the job it may succeed. I had similar issues before when jobs fail due to i.e. internet connectivity.

**Review by manuelcandales — APPROVED** [review]

**Pull request closed without merging**
