### PR TITLE
Reland Add more prebuilt artifacts

### PR DESCRIPTION
**Pull request by kirklandsign**
Summary: Build for different ABI in prebuild.

Differential Revision: D56530383

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Comment by huydhn** [comment]
Just FYI, if you want the authentication with AWS on `Android / test-llama-app / mobile-job` to pass, choose not to use a forked PR when exporting the PR.  Only ET repo has permission to authenticate with AWS.

**Comment by kirklandsign** [comment]
> Just FYI, if you want the authentication with AWS on `Android / test-llama-app / mobile-job` to pass, choose not to use a forked PR when exporting the PR. Only ET repo has permission to authenticate with AWS.

Thank you Huy! I guess we are good for this one, since it won't change android build behavior, but just add artifacts?

**Comment by huydhn** [comment]
Yup, that is just an FYI.

**Pull request closed without merging**
