### PR TITLE
[llava][21/N] Add llava runner test binary and build script

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #4667

Add a `main.cpp` and CMakeLists.txt for llava runner. This runner takes in an image in the format of `.pt` (a serialized pytorch model) along with text prompt. It will generate text tokens in a way similar to llama runner.

Run `build.sh` to build the runner.

To serialize the image into a `.pt` file, run the following script:

```python
import torch
from torch import nn

copy = torch.tensor(resized)
m = nn.Module()
par = nn.Parameter(copy, requires_grad=False)
m.register_parameter("0",par)
tensors = torch.jit.script(m)
tensors.save("image.pt")
```

To run the runner, use the following command:

```
cmake-out/examples/models/llava/llava_main                                                               \    
    --tokenizer_path tokenizer.bin                                                                                    \
    --model_path llava_kv_768.pte                                                                                  \
    --prompt "\nWhat are the things I should be cautious about when I visit here?"  \
    --image_path image.pt                                                                                                \
    --temperature 0
```

Differential Revision: [D61146432](https://www.internalfb.com/diff/D61146432)

### CODE REVIEW

**Review by lucylq — APPROVED** [review]
Lgtm after linter/nits, thank you

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61362903).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61146432).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61146432).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61146432).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61146432).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61146432).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61146432).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61146432).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61146432).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61146432).

**Pull request merged**
