### PR TITLE
Fix backends/arm test after _skip_dim_order update

### PR DESCRIPTION
**Pull request by zingo**
This fixes the backends/arm unit tests

### CODE REVIEW

**Comment by zingo** [comment]
This will hopefully fix the arm test problem after the changes in  https://github.com/pytorch/executorch/pull/2205 / https://github.com/pytorch/executorch/pull/3521

**Comment by zingo** [comment]
https://github.com/pytorch/executorch/pull/3123 might have introduced a problem when TOSA is not installed.

**Comment by digantdesai** [comment]
cc @Gasoonjia - let's make sure these tests are also working for dim-order related stuff.

**Review by digantdesai — APPROVED** [review]
Thanks @zingo

**Review by larryliu0820 — APPROVED** [review]

**Pull request closed without merging**
