### PR TITLE
[llava][20/N] Add llava runner using building blocks in e/llm/runner

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #4666

Add llava runner that uses runner lib in `extension/llm/runner`.

Differential Revision: [D61292846](https://our.internmc.facebook.com/intern/diff/D61292846)

### CODE REVIEW

**Comment by lucylq** [comment]
Very clean way to build the runner from components, thanks for all the work! Import to internal?

**Review by lucylq — APPROVED** [review]
Lgtm after linter

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61292846).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61292846).

**Pull request merged**
