### PR TITLE
add CI job for eval_llama with wikitext task

### PR DESCRIPTION
**Pull request by helunwencser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #6344
* #6337
* __->__ #6336

Differential Revision: [D64565304](https://our.internmc.facebook.com/intern/diff/D64565304)

### CODE REVIEW

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64565304).

**Review by cccclai — APPROVED** [review]
Great to have more test coverage :)

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64565304).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64565304).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64565304).

**Pull request closed without merging**
