### PR TITLE
qnn source code changes

### PR DESCRIPTION
**Pull request by cccclai**
Differential Revision: D60929838

### CODE REVIEW

**Comment by cccclai** [comment]
@chiwwang hey I have some questions regarding the source code change here. The context is that I'm trying to use buck build, however buiding fails. I took a look and seems like the suggested code change makes sense. It's weird that cmake build is fine. Any context on the source code change here?

**Comment by chiwwang** [comment]
mmmm... strange. I think it should be`->`.
The type of`tensor_type` seems to be `IndirectHelper< ::flatbuffers::Offset< qcir::Tensor> >::return_type`
It looks like a pointer in [this specialization](https://github.com/google/flatbuffers/blob/fb9afbafc7dfe226b9db54d4923bfb8839635274/include/flatbuffers/buffer.h#L110). Some comments are [here](https://github.com/google/flatbuffers/blob/fb9afbafc7dfe226b9db54d4923bfb8839635274/include/flatbuffers/buffer.h#L85).

Could you share buck build commands? We can also try it.
A quick guess is, maybe something wrong in buck cache... if I remember correctly, buck/bazel comes with stronger cache behaviors 🤔 

@haowhsu-quic , could you please also take a look?

**Comment by haowhsu-quic** [comment]
Sorry for the late reply, I did some survey but could not figure this out. It looks a pointer type from source code.
Does this issue still persist?

**Comment by cccclai** [comment]
yeah the issue still persist...it's really strange

**Comment by cccclai** [comment]
The issue is resovled with https://github.com/pytorch/executorch/pull/4716. Looks like it's related to the flatc version. Thanks for helping.

**Pull request closed without merging**
