### PR TITLE
[For testing/docker build] Update buck to 2024-05-15

### PR DESCRIPTION
**Pull request by kirklandsign**

### CODE REVIEW

**Comment by mergennachin** [comment]
I think there are more references to the old buck version (ci configs as well as docs). 

https://github.com/search?q=repo%3Apytorch%2Fexecutorch%202024-02-15&type=code

we need to update them all atomically

**Comment by kirklandsign** [comment]
Need to update https://ossci-macos.s3.amazonaws.com/buck2-aarch64-apple-darwin.zst

I asked Huy about this.

Meanwhile, I will wait for this round of CI to give me signals and I will push the commit to fix other references to buck version

**Comment by kirklandsign** [comment]
Signals are promising so far.

**Comment by kirklandsign** [comment]
Signals are good. Now use https://github.com/pytorch/executorch/pull/3698

**Pull request closed without merging**
