### PR TITLE
Add MobileNetV2 unit test for Arm backend

### PR DESCRIPTION
**Pull request by oscarandersson8218**
Adds a MobileNetV2 unit test for Arm backend.

### CODE REVIEW

**Comment by Jerry-Ge** [comment]
LGTM. Note: this test case is commented out for now since it's not fully supported.

**Comment by freddan80** [comment]
Maybe this is note needed now since we have https://github.com/pytorch/executorch/pull/1971 in flight..?

**Comment by oscarandersson8218** [comment]
@freddan80 Agree, closing this.

**Pull request closed without merging**
