### PR TITLE
[0.2.1 Release] Update third-party/pytorch to 2.3.1 rc

### PR DESCRIPTION
**Pull request by mcr229**
Update third-party/pytorch to the RC for PyTorch 2.3.1

### CODE REVIEW

**Comment by mergennachin** [comment]
what git hash did you use for the new git submodule?

**Comment by mcr229** [comment]
@mergennachin I checked out the latest commit of release/2.3 branch which is 63d5e9221bedd1546b7d364b5ce4171547db12a9

https://github.com/pytorch/pytorch/commits/release/2.3/

**Comment by guangy10** [comment]
FYI, the prebuilt binary version should be updated to 2.3.1 as well: https://github.com/pytorch/executorch/blob/release/0.2/install_requirements.sh#L66
Maybe you plan to do it in a separate PR?

**Comment by guangy10** [comment]
> FYI, the prebuilt binary version should be updated to 2.3.1 as well: https://github.com/pytorch/executorch/blob/release/0.2/install_requirements.sh#L66 Maybe you plan to do it in a separate PR?

I think you may want to use the commit hash that v2.3.1-rc3 tag sits: https://github.com/pytorch/pytorch/tree/v2.3.1-rc3

**Comment by mergennachin** [comment]
@mcr229 

> I had a pr that did this update but failed because 2.3.1 was not a real branch, since it reuses the 2.3.0 branch. Which is why I refrained from making these changes.

I think there are two separate things. There's a pin that uses a release branch to check out PT and build. It is used in CI. I think your previous PR tried to change that. 

What @guangy10  is mentioning is the install_requirements.sh script that developers use to install and setup executorch. That needs to be updated.

**Comment by mcr229** [comment]
@mergennachin @guangy10
Sounds good, I updated the third-party/pytorch commit to the tag v2.3.1-rc3 by

```
cd third-party/pytorch
git checkout tags/v2.3.1-rc3  
```

I also updated the install requirements to the patched releases.

**Review by dbort — APPROVED** [review]

**Review by dbort — DISMISSED** [review]
Actually could you also update the versions in https://github.com/pytorch/executorch/blob/d16aaa5890fdee8c07113664e56b73242035191d/pyproject.toml#L63-L65 so that the pip package uses these versions, too?

**Review by mergennachin — APPROVED** [review]

**Review by mergennachin — APPROVED** [review]

**Pull request merged**
