### PR TITLE
Arm backend: Track target memory usage

### PR DESCRIPTION
**Pull request by zingo**
This adds memory stats API to the Memory Allocator and make it possible for the backends to track and report runtime memory usage.

### CODE REVIEW

**Review by digantdesai — APPROVED** [review]

**Comment by digantdesai** [comment]
rebase please?

**Comment by zingo** [comment]
Oh sorry, no problem Ill get my number in some other way. Sorry for the breakage.

**Comment by zingo** [comment]
Replaced by https://github.com/pytorch/executorch/pull/5788

**Pull request closed without merging**
