### PR TITLE
[flatbuffer] Add constant segment to export options

### PR DESCRIPTION
**Pull request by lucylq**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #1406

Differential Revision: [D52137846](https://our.internmc.facebook.com/intern/diff/D52137846)

### CODE REVIEW

**Review by iseeyuan — APPROVED** [review]
LGTM. Thanks @lucylq !

**Comment by lucylq** [comment]
@lucylq has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D52137846).

**Comment by lucylq** [comment]
@lucylq has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D52137846).

**Comment by lucylq** [comment]
@lucylq has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D52137846).

**Comment by lucylq** [comment]
@lucylq has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D52137846).

**Comment by lucylq** [comment]
@lucylq has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D52137846).

**Pull request closed without merging**
