### PR TITLE
Add Llama3.2 CoreML ANE to benchmark

### PR DESCRIPTION
**Pull request by guangy10**
Llama3.2 Core ML ANE. Require iOS 18. @huydhn created a new device pool with iOS 18+. We will run the ANE path using this device pool.

Job link: https://github.com/pytorch/executorch/actions/runs/12423590967

### CODE REVIEW

**Comment by guangy10** [comment]
@huydhn We may need a way to specify the OS version together with the device pool name as some configs may require to run on/above certain OS versions. Running Llama3.2 w/ Core ML ANE requires minimal iOS 18.0 for example.

**Comment by guangy10** [comment]
The job running on iPhone 15 w/ iOS 18.0 actually passed. Here is the [log](https://github.com/pytorch/executorch/actions/runs/12405648153/job/34633342752?pr=7399#step:14:2521) showing that. Checked [Customer_Artifacts.zip](https://gha-artifacts.s3.amazonaws.com/device_farm/12405648153/1/arn_aws_devicefarm_us-west-2_308535385114_artifact_02a2cf0f-6d9b-45ee-ba1a-a086587469e6_a65793d6-6563-4b3d-abdd-6f700572cf69_00003_00001_00000_00003_Customer_Artifacts.zip) as well, all 3 tests passed. However, at the end of the test, it still mark the run FAILED at the end: https://github.com/pytorch/executorch/actions/runs/12405648153/job/34633342752?pr=7399#step:14:2567. cc: @huydhn

**Comment by huydhn** [comment]
> @huydhn We need the ability to specify the OS version together to select devices from the device pool as some configs may require to run on/above certain OS versions. Running Llama3.2 w/ Core ML ANE requires minimal iOS 18.0 for example.

It could be done by creating a new device pool.  I go ahead and create one ready.  You can use `arn:aws:devicefarm:us-west-2:308535385114:devicepool:02a2cf0f-6d9b-45ee-ba1a-a086587469e6/12c8b15c-8d03-4e07-950d-0a627e7595b4` for iPhone 15 devices with iOS > 18.0

**Review by huydhn — APPROVED** [review]

**Comment by guangy10** [comment]
Okay, we can see the CoreML ANE is working on iSO 18. Going to use the new device pool for this path

**Review by metascroy — APPROVED** [review]

**Pull request merged**
