### PR TITLE
Qualcomm AI Engine Direct - wav2letter e2e example

### PR DESCRIPTION
**Pull request by haowhsu-quic**
Summary
- enable wav2letter e2e example

### CODE REVIEW

**Comment by haowhsu-quic** [comment]
Hi @cccclai, please have a look on this, thank you.
I wonder if we could land https://github.com/pytorch/executorch/pull/5543? It will be helpful for us to continue enabling more oss models.

**Comment by cccclai** [comment]
> Hi @cccclai, please have a look on this, thank you. I wonder if we could land #5543? It will be helpful for us to continue enabling more oss models.

Yes for sure. Sorry for getting late on this, and thank you for enabling more models!

**Comment by guangy10** [comment]
When this model is enabled can you please update the CI to cover this model?
  1. Update the test script: https://github.com/pytorch/executorch/blob/main/.ci/scripts/test_model.sh#L147
  2. Update the nightly benchmark workflow to see the perf: https://github.com/pytorch/executorch/blob/main/.github/workflows/android-perf.yml#L87

**Review by cccclai — APPROVED** [review]

**Comment by haowhsu-quic** [comment]
Hi @guangy10, this model requires `pretrained_weight` as an input argument which requires getting checkpoint in advance.
I think the downloading process and extra argument may change the script logic now. Do you have suggestions?

**Comment by cccclai** [comment]
If there are extra efforts to add them to CI, maybe we can have a follow up on that. Thoughts? @guangy10

**Pull request merged**
