### PR TITLE
Update torch nightly version to dev20240205

### PR DESCRIPTION
**Pull request by Jerry-Ge**
This PR is causing issues (https://github.com/pytorch/pytorch/commit/bf4e171539756ed1f49e3e45122d003760d21f5f) with the un-updated torch nightly version. 

```
AttributeError: 'InputSpec' object has no attribute 'persistent'
```

20240205 Nightly release: https://github.com/pytorch/pytorch/commit/e795fa298a3ac0611ec611bbf716fd1d5d9f7fa4

### CODE REVIEW

**Review by angelayi — APPROVED** [review]

**Comment by digantdesai** [comment]
You need to update the submodule as well see PR #1808 for example.

**Review by digantdesai — CHANGES_REQUESTED** [review]
.

**Comment by Jerry-Ge** [comment]
> You need to update the submodule as well see PR #1808 for example.

ah, thanks. How do I find the correct HASH for `dev20240205` ?

**Comment by cccclai** [comment]
https://github.com/pytorch/executorch/pull/1855 is landed instead because this pr needs some extra changes. Thanks for sending the fix!

**Pull request closed without merging**
