### PR TITLE
Qualcomm AI Engine Direct - Fold_Quant Enabled

### PR DESCRIPTION
**Pull request by winskuo-quic**
Summary:

- Enabled fold_quant as default option during convert_pt2e
- Embedding OP Removed:
  1. Embedding OP has input index data type in int64, which is not supported by QNN.
  2. When enabling "fold_quant" option, the parameters from fallback embedding will go through dequantization process to get its floating value. This operation will lead to a significant loss in accuracy.
  3. Therefore, we have decided to remove this operation and its quantization config. This can largely benefit models that is sensitive to parameters (e.g., mobilebert) by using mix precision.

### CODE REVIEW

**Comment by winskuo-quic** [comment]
Hi @jerryzh168,
This PR is used to resolve errors encountered after fold_quant is enabled.
Please have a look at this PR.
Thanks

**Comment by winskuo-quic** [comment]
Hi @kimishpatel,
This PR is to enable fold_quant option during convert_pt2e.
The master branch running QNN AOT will fail and need to merge this ticket in order to resolve the issue.
Please take a look at this PR.
Thanks

**Review by jerryzh168 — APPROVED** [review]
thanks! looks good to me. wondering why embedding will have a large accuracy loss?

also I'm turning on fold_quantize by default in pytorch: https://github.com/pytorch/pytorch/pull/118605 and currently trying to remove `fold_quantize` flag

**Comment by winskuo-quic** [comment]
> thanks! looks good to me. wondering why embedding will have a large accuracy loss?
> 
> also I'm turning on fold_quantize by default in pytorch: [pytorch/pytorch#118605](https://github.com/pytorch/pytorch/pull/118605) and currently trying to remove `fold_quantize` flag

Hi @jerryzh168,
Thanks for reviewing the PR. The reason is that Embedding OP has input index data type in int64, and we believe representing a 64-bit data with 8-bit data could lead to a significant loss in accuracy.

Also, thanks for sharing the current status on fold_quant. However, QNN AOT will fail in current mainline without this PR.
By any chance, could you share the schedule of how the PR is going to merge?
Thanks

**Comment by jerryzh168** [comment]
I can check to see how I can merge it

**Comment by kimishpatel** [comment]
Please fix lint error

**Comment by winskuo-quic** [comment]
Hi @kimishpatel,
Thanks for reviewing my PR.
However, when I look into lint errors, it seems like those files that are showing errors are not  the files that I modified, and they are not under "qualcomm" directory.

**Comment by kimishpatel** [comment]
> Hi @kimishpatel, Thanks for reviewing my PR. However, when I look into lint errors, it seems like those files that are showing errors are not the files that I modified, and they are not under "qualcomm" directory.

ok no worries then. If you see them on master (https://hud.pytorch.org/hud/pytorch/executorch/main/1?per_page=50) then ignore this. Else just rebase.

**Comment by haowhsu-quic** [comment]
Looks like the lint error was not related to this change, will ask the author to rebase this tomorrow.

**Comment by winskuo-quic** [comment]
Hi @kimishpatel , @haowhsu-quic,
Thanks for the reminder. I have just rebased.

**Comment by haowhsu-quic** [comment]
I wonder if you could also help merge https://github.com/pytorch/executorch/pull/1531? It would be great to have this. Thank you.

**Comment by kimishpatel** [comment]
Some merge conflicts, you may have to rebase

**Comment by haowhsu-quic** [comment]
I have rebased it after last PR import (https://github.com/pytorch/executorch/pull/1773/commits/9f4b72898030d37c2d025078f65a329d6eb776c6), could you check again? Thank you.

**Pull request closed without merging**
