### PR TITLE
[llava][17/N] Move util.h into /e/llm/runner

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #4588
* #4585
* #4567
* #4556

So that it can be reused

Differential Revision: [D60938984](https://our.internmc.facebook.com/intern/diff/D60938984)

### CODE REVIEW

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60938984).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60938984).

**Review by iseeyuan — APPROVED** [review]
LGTM.

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60938984).

**Pull request merged**
