### PR TITLE
Compile and deploy QNN models to S24

### PR DESCRIPTION
**Pull request by guangy10**

### CODE REVIEW

**Comment by guangy10** [comment]
Scheduled job: https://github.com/pytorch/executorch/actions/runs/10746356523

**Review by huydhn — APPROVED** [review]
LGTM! Let's see if the benchmark job passes

**Comment by guangy10** [comment]
> LGTM! Let's see if the benchmark job passes

We should expect (stories110M, xnnpack) working on S24. That's the only thing we should look at. Other models will fail until @kirklandsign has the test-spec updated for the minibench and the minibench is built with both xnn & qnn backends.

**Comment by guangy10** [comment]
```
INFO:root:mobile-job-android-10746356523-1-2024-09-06-BpXToJcY FAILED 
INFO:root:  Samsung Galaxy S24 FAILED 
```
https://github.com/pytorch/executorch/actions/runs/10746356523/job/29807680315

**Pull request closed without merging**
