### PR TITLE
Qualcomm AI Engine Direct - Optimization and fix mutable buffer issue

### PR DESCRIPTION
**Pull request by shewu-quic**
Summary:
- Add a pass to convert linear to conv2d: We found the accuracy drop because of QNN Linear op in llama3. And it will be fixed with convert linear to conv2d pass.
- Workaround the issue about mutable buffer for index_put op: We add a pass to replace the input of index_put op. Under the workaround, it will result in performance regression.
- Insert copy op for int64 inputs to convert int64 to int32 in i64toi32 pass
- Support QNN RMS Norm and use native rms norm in llama_transformer
- Add a pass to compose rms norm

**Note that QNN supports RMS Norm after 2.25.**

### CODE REVIEW

**Comment by cccclai** [comment]
This looks awesome, seems like it generates results with good quality, do I understand it correctly? 

Regarding this
> We found that a memory issue about [tokenizer loading in runtime](https://github.com/pytorch/executorch/blob/3cf9237af1b6743cfe5293ac333efc39951adf49/examples/models/llama2/runner/runner.cpp#L75) on mainline branch.

How do I repro and how did you still manage to generate result with the OOM issue?

**Comment by cccclai** [comment]
Looks like you fallback `aten.embedding.default` to cpu, is it how you resolve the OOM issue?

**Comment by shewu-quic** [comment]
> Looks like you fallback `aten.embedding.default` to cpu, is it how you resolve the OOM issue?

Yes, I currently fallback it to cpu, and it could work on 16GB device.
I think [this change](https://github.com/pytorch/executorch/blob/a7e6164029e4b53da2025eec82c3a6c8b56989e7/examples/models/llama2/export_llama_lib.py#L556) benefits memory usage, because it seems to need more spill buffer than our calculation.
We will try to resolve our calculation in the follow-up PR.

But I think we could try to quantize embedding op to reduce memory usage

**Comment by shewu-quic** [comment]
> This looks awesome, seems like it generates results with good quality, do I understand it correctly?
> 

Yes, I think that good news is to generate good result.

> Regarding this
> 
> > We found that a memory issue about [tokenizer loading in runtime](https://github.com/pytorch/executorch/blob/3cf9237af1b6743cfe5293ac333efc39951adf49/examples/models/llama2/runner/runner.cpp#L75) on mainline branch.
> 
> How do I repro and how did you still manage to generate result with the OOM issue?

I think you could reproduce it in this PR.
For now, I just comment out the line about loading BPETokenizer to workaround this issue.
And I also have tried moving the tokenizer loading forward to before the model loading but it didn't work on my 16GB device. It seems failed to load tokenizer.model (llama3 tokenizer), it will be killed.
image

**Comment by cccclai** [comment]
> For now, I just comment out the line about loading BPETokenizer to workaround this issue.

Hmm I'm a bit confused. Isn't BPETokenizer necessary for prompt decoding and encoding? How do you generate result without tokenizer?

**Comment by shewu-quic** [comment]
> > For now, I just comment out the line about loading BPETokenizer to workaround this issue.
> 
> Hmm I'm a bit confused. Isn't BPETokenizer necessary for prompt decoding and encoding? How do you generate result without tokenizer?

Because in llama3 we should use tik_tokenizer to do encoding and decoding, right.

**Comment by cccclai** [comment]
> Because in llama3 we should use tik_tokenizer to do encoding and decoding, right.

Hmm if we use llama3, how do we ending up using bpe tokenizer..?

**Review by cccclai — APPROVED** [review]
Looks great! Mind holding a bit before https://github.com/pytorch/executorch/pull/4942 is merged? Still working with the team to land this.

**Comment by cccclai** [comment]
https://github.com/pytorch/executorch/pull/4942 is just approved. Will merge it asap

**Comment by shewu-quic** [comment]
> #4942 is just approved. Will merge it asap

Thanks for your effort. There is some fails for llama runner test in PR check. Is this expected?

**Comment by shewu-quic** [comment]
> > Because in llama3 we should use tik_tokenizer to do encoding and decoding, right.
> 
> Hmm if we use llama3, how do we ending up using bpe tokenizer..?

Ohh, could we use bpe tokenizer for llama3?
 BTW I try to run xnnpack on my device, I encounter the same OOM issue in runner due to [bpe tokenizer loading in runtime](https://github.com/pytorch/executorch/blob/3cf9237af1b6743cfe5293ac333efc39951adf49/examples/models/llama2/runner/runner.cpp#L75)

**Comment by cccclai** [comment]
> > #4942 is just approved. Will merge it asap
> 
> Thanks for your effort. There is some fails for llama runner test in PR check. Is this expected?

That is unrelated. It's resolved after rebase.

**Comment by cccclai** [comment]
> > > Because in llama3 we should use tik_tokenizer to do encoding and decoding, right.
> > 
> > 
> > Hmm if we use llama3, how do we ending up using bpe tokenizer..?
> 
> Ohh, could we use bpe tokenizer for llama3? BTW I try to run xnnpack on my device, I encounter the same OOM issue in runner due to [bpe tokenizer loading in runtime](https://github.com/pytorch/executorch/blob/3cf9237af1b6743cfe5293ac333efc39951adf49/examples/models/llama2/runner/runner.cpp#L75)

Hmm I think we will need to use tiktokenizer for llama3. bpe tokenizer is only for llama2. 

> > > Because in llama3 we should use tik_tokenizer to do encoding and decoding, right.
> > 
> > 
> > Hmm if we use llama3, how do we ending up using bpe tokenizer..?
> 
> Ohh, could we use bpe tokenizer for llama3? BTW I try to run xnnpack on my device, I encounter the same OOM issue in runner due to [bpe tokenizer loading in runtime](https://github.com/pytorch/executorch/blob/3cf9237af1b6743cfe5293ac333efc39951adf49/examples/models/llama2/runner/runner.cpp#L75)

Hmm I think we should just use tiktokenizer for llama3...are you using llama3 tokenizer?

**Comment by cccclai** [comment]
> > > Because in llama3 we should use tik_tokenizer to do encoding and decoding, right.
> > 
> > 
> > Hmm if we use llama3, how do we ending up using bpe tokenizer..?
> 
> Ohh, could we use bpe tokenizer for llama3? BTW I try to run xnnpack on my device, I encounter the same OOM issue in runner due to [bpe tokenizer loading in runtime](https://github.com/pytorch/executorch/blob/3cf9237af1b6743cfe5293ac333efc39951adf49/examples/models/llama2/runner/runner.cpp#L75)

Hmm I think we need to use tik tokenizer for llama3. I thought [it just falls back to bpe tokenizer if it fails](https://github.com/pytorch/executorch/blob/97396091080d152a09c20d4fa5a7ef3981b2ed48/examples/models/llama2/runner/runner.cpp#L83-L84).  Are you using llama3 tokenizer?

**Comment by shewu-quic** [comment]
> Hmm I think we need to use tik tokenizer for llama3. I thought [it just falls back to bpe tokenizer if it fails](https://github.com/pytorch/executorch/blob/97396091080d152a09c20d4fa5a7ef3981b2ed48/examples/models/llama2/runner/runner.cpp#L83-L84). Are you using llama3 tokenizer?

Yes, I am using llama3 tokenizer.
image

Yes, I agree with your mention. It should be failed to load with bpe tokenizer and change to load tik tokenizer.
However, when it load with bpe, it will raise OOM.

**Comment by shewu-quic** [comment]
> > > #4942 is just approved. Will merge it asap
> > 
> > 
> > Thanks for your effort. There is some fails for llama runner test in PR check. Is this expected?
> 
> That is unrelated. It's resolved after rebase.

Got it. I thought my problem so I add a transform to replace rms norm instead of changing in llama_transform.py

**Comment by cccclai** [comment]
> Yes, I agree with your mention. It should be failed to load with bpe tokenizer and change to load tik tokenizer. However, when it loaded with bpe, it will raise OOM. So, it would not continue to load tik tokenizer. Therefore, I comment out those lines and it could normally work.

Hmm I think [the default is tiktokenizer](https://github.com/pytorch/executorch/blob/97396091080d152a09c20d4fa5a7ef3981b2ed48/examples/models/llama2/runner/runner.cpp#L73C16-L73C38), and if it fails, [it will be reset and load bpe tokenizer](https://github.com/pytorch/executorch/blob/97396091080d152a09c20d4fa5a7ef3981b2ed48/examples/models/llama2/runner/runner.cpp#L82-L83).

**Comment by shewu-quic** [comment]
> > Yes, I agree with your mention. It should be failed to load with bpe tokenizer and change to load tik tokenizer. However, when it loaded with bpe, it will raise OOM. So, it would not continue to load tik tokenizer. Therefore, I comment out those lines and it could normally work.
> 
> Hmm I think [the default is tiktokenizer](https://github.com/pytorch/executorch/blob/97396091080d152a09c20d4fa5a7ef3981b2ed48/examples/models/llama2/runner/runner.cpp#L73C16-L73C38), and if it fails, [it will be reset and load bpe tokenizer](https://github.com/pytorch/executorch/blob/97396091080d152a09c20d4fa5a7ef3981b2ed48/examples/models/llama2/runner/runner.cpp#L82-L83).

Woops, it changed yesterday.... :)
Great, sorry to bother you.

**Comment by cccclai** [comment]
> > > > #4942 is just approved. Will merge it asap
> > > 
> > > 
> > > Thanks for your effort. There is some fails for llama runner test in PR check. Is this expected?
> > 
> > 
> > That is unrelated. It's resolved after rebase.
> 
> Got it. I thought my problem so I add a transform to replace rms norm instead of changing in llama_transform.py

Actually for this one, do you remember which job is failing? Is it the [test-llama-runner-qnn job[(https://hud.pytorch.org/hud/pytorch/executorch/main/1?per_page=50&name_filter=test-llama-runner-qnn)? Then it's the qnn llama end to end job...

**Comment by shewu-quic** [comment]
> > > > > #4942 is just approved. Will merge it asap
> > > > 
> > > > 
> > > > Thanks for your effort. There is some fails for llama runner test in PR check. Is this expected?
> > > 
> > > 
> > > That is unrelated. It's resolved after rebase.
> > 
> > 
> > Got it. I thought my problem so I add a transform to replace rms norm instead of changing in llama_transform.py
> 
> Actually for this one, do you remember which job is failing? Is it the [test-llama-runner-qnn job[(https://hud.pytorch.org/hud/pytorch/executorch/main/1?per_page=50&name_filter=test-llama-runner-qnn)? Then it's the qnn llama end to end job...

Oh, for this test, it needs to use qnn 2.25 or above

**Comment by cccclai** [comment]
> Oh, for this test, it needs to use qnn 2.25 or above due to RMS Norm support

I see, can we update these lines then? https://github.com/pytorch/executorch/blob/main/.ci/scripts/setup-qnn-deps.sh#L15-L18

**Comment by shewu-quic** [comment]
> > Oh, for this test, it needs to use qnn 2.25 or above due to RMS Norm support
> 
> I see, can we update these lines then? https://github.com/pytorch/executorch/blob/main/.ci/scripts/setup-qnn-deps.sh#L15-L18

Hi, 
I find there is no libc++.so in ${QNN_SDK_ROOT}/lib/x86_64-linux-clang.
We need to manually install it in system.

**Comment by cccclai** [comment]
@shewu-quic 

I see, let me get some help from internal teams on this. In the worst case we disable the CI

**Comment by cccclai** [comment]
The backup plan is to delete the llama qnn ci job temporarily and resume it later, essentially, 

1. remove the qnn version bump
2. delete these lines https://github.com/pytorch/executorch/blob/7122d310844ba701db1f45a13ccaa8c5a002fc89/.github/workflows/pull.yml#L377-L409 
3. merge this pr
4. recover the test after we figure out how to do it properly

**Comment by cccclai** [comment]
https://github.com/pytorch/executorch/pull/4942 is merged, could you rebase, and remove the llama test?

**Comment by shewu-quic** [comment]
> #4942 is merged, could you rebase, and remove the llama test?

Thanks, I have rebased and remove the test.
And then we could file another PR to recover it, somehow, I think that we could use apt get to install libc++ or cp it from older QNN library :)

**Comment by cccclai** [comment]
Hi can you add this change as it breaks some internal tests (we use buck internally)
```
--- a/fbcode/executorch/examples/models/llama2/TARGETS
+++ b/fbcode/executorch/examples/models/llama2/TARGETS
@@ -71,6 +71,7 @@
         "export_llama_lib.py",
         "model.py",
         "source_transformation/quantize.py",
+        "source_transformation/rms_norm.py",
         "source_transformation/rope.py",
         "source_transformation/sdpa.py",
     ],
```

**Comment by cccclai** [comment]
Looks like the patch is not part of the new commit. Did I miss anything?

**Comment by shewu-quic** [comment]
> Looks like the patch is not part of the new commit. Did I miss anything?
> 
> edit: Actually saw them. Thanks!

Do I need to rebase again?

**Comment by cccclai** [comment]
Hey sorry could you rebase again? I'm having issues to merge

**Comment by cccclai** [comment]
Hey could you rebase? I'm having issues landing....

**Comment by shewu-quic** [comment]
@cccclai
done.

**Pull request merged**
