### PR TITLE
Qualcomm AI Engine Direct - HardSigmoid follow up for FP16 / Test cases complement

### PR DESCRIPTION
**Pull request by chuntl**
Summary:
- make HardSigmoid more compact in FP16
- add online prepare utitlity test case
- add test case for export_example.py

### CODE REVIEW

**Review by cccclai — APPROVED** [review]

**Comment by chuntl** [comment]
Hi @cccclai ,

Thanks for the approval, I have rebased this PR to mainline.
May I know if you could help to check it and merge this PR again, thank you!

**Comment by cccclai** [comment]
> Hi @cccclai ,
> 
> Thanks for the approval, I have rebased this PR to mainline. May I know if you could help to check it and merge this PR again, thank you!

Hi sorry lost track of this pr - landing now

**Comment by cccclai** [comment]
It seems like CI is still failing, but main should be stable, mind rebasing again?

**Comment by chuntl** [comment]
> It seems like CI is still failing, but main should be stable, mind rebasing again?

Sure, but it's merged now, may I know if I need to rebase it again?

**Comment by cccclai** [comment]
Oh it should be good. It might due to sync issue. Thank you for making the change!

**Pull request closed without merging**
