### PR TITLE
[llava][19/N] Add multimodal runner base class and build file

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #4667
* #4666
* __->__ #4665

Add multimodel runner class and CMakeLists.txt for building it.

Differential Revision: [](https://our.internmc.facebook.com/intern/diff/)

Differential Revision: [D61249552](https://our.internmc.facebook.com/intern/diff/D61249552)

### CODE REVIEW

**Comment by lucylq** [comment]
looks good - import to internal?

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61249552).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61249552).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61249552).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61249552).

**Review by lucylq — APPROVED** [review]

**Pull request merged**
