### PR TITLE
Add CastInt64ToInt32Pass

### PR DESCRIPTION
**Pull request by Erik-Lundell**
Integer placeholders, for example in this examples x = torch.Tensor([1.]) + 1
Are by default lowered as int64 tensors.

As int64 is not a valid TOSA dtype, we cast these
tensors to int32.

Reference:
https://www.mlplatform.org/tosa/tosa_spec.html#_supported_number_formats

Change-Id: Ice59625b7fd68ff3a544ee4648fe05f69b9333e6

### CODE REVIEW

**Comment by digantdesai** [comment]
CI issues?

**Comment by zingo** [comment]
Yes it was caused by the Pythorch 2.5->2.6 update that was merged yesterday
Fix is here https://github.com/pytorch/executorch/pull/5843
See https://github.com/pytorch/executorch/issues/5832 for more info.

**Review by digantdesai — APPROVED** [review]
Thanks.

**Comment by digantdesai** [comment]
Can't tell why the arm-backend job is failing, seems like infra issue, because FVP returned 0. Let me rerun it.

**Pull request closed without merging**
