### PR TITLE
Qaulcomm AI Engine Direct - Fix quantization annotation for per channel quant

### PR DESCRIPTION
**Pull request by shewu-quic**
summary:

- Fix the 8a8w config in custom annotation
- Enable to set act observer and symmetric argument for per channel quant
- Remove unuse custom annotation in llama.py

### CODE REVIEW

**Comment by shewu-quic** [comment]
Hi @cccclai,

The PR is to enable to set the act_observer for per-channel quant which to align the observer with other nodes.
Could you help to take a look?

Thanks,
Hutton

**Comment by cccclai** [comment]
@navsud can you help with verifying

**Review by navsud — APPROVED** [review]
LGTM

Thanks for the update... Without this, the act observers were not consistent across the graph, especially when we want to use MinMaxObserver for 16-bit activations.

**Review by cccclai — APPROVED** [review]
Thanks!

**Pull request merged**
