### PR TITLE
Add cat/stack ops to generic annotator

### PR DESCRIPTION
**Pull request by SaoirseARM**
- Adds capability to annotator ops with more than one input i.e cat/stack
- Adds some missing data layout ops to generic_annotator
- Removes Quantize_io from tests which are covered by generic annotator
- Removes duplicates from is_share_obs_or_fq_op

### CODE REVIEW

**Review by digantdesai — APPROVED** [review]

**Comment by digantdesai** [comment]
Found issues internally, can you please fix it? 🙏 
```
executorch/backends/arm/quantizer/quantization_annotation/generic_annotator.py:83:18 Incompatible parameter type [6]: In call `_annotate_input_qspec_map`, for 2nd positional argument, expected `Node` but got `Union[List[Node], Node]`.
```
```
executorch/backends/arm/quantizer/quantization_annotation/generic_annotator.py:85:58 Incompatible parameter type [6]: In call `torch.ao.quantization.quantizer.quantizer.SharedQuantizationSpec.__init__`, for 1st positional argument, expected `Union[Tuple[Node, Node], Node]` but got `Tuple[Union[List[Node], Node], typing.Any]`.
```

**Comment by SaoirseARM** [comment]
> Found issues internally, can you please fix it? 🙏
> 
> ```
> executorch/backends/arm/quantizer/quantization_annotation/generic_annotator.py:83:18 Incompatible parameter type [6]: In call `_annotate_input_qspec_map`, for 2nd positional argument, expected `Node` but got `Union[List[Node], Node]`.
> ```
> 
> ```
> executorch/backends/arm/quantizer/quantization_annotation/generic_annotator.py:85:58 Incompatible parameter type [6]: In call `torch.ao.quantization.quantizer.quantizer.SharedQuantizationSpec.__init__`, for 1st positional argument, expected `Union[Tuple[Node, Node], Node]` but got `Tuple[Union[List[Node], Node], typing.Any]`.
> ```

Apologies for the delay on this! It should be fixed now. 

Thanks, 
Saoirse

**Pull request merged**
