### PR TITLE
Rollback pytorch pin to 01/10

### PR DESCRIPTION
**Pull request by larryliu0820**
Summary:
In https://github.com/pytorch/executorch/pull/1586 I updated the pytorch pin to 01/11 but actually the nightly build is broken so torchvision and torchaudio don't have nightly build. This leads to issues when we run `bash install_requirements.sh`.

This rollback the pin to 01/10 and will update to the latest once nightly build recovers.

Reviewed By: dbort

Differential Revision: D52747830

### CODE REVIEW

**Comment by huydhn** [comment]
@larryliu0820 I'm seeing an ET build failure from PyTorch after https://github.com/pytorch/pytorch/pull/117378.  The failure is in https://github.com/pytorch/pytorch/pull/117003, i.e. https://github.com/pytorch/pytorch/actions/runs/7522657336/job/20474959526#step:5:9155

```
AssertionError: Found an operator that we could not generate an out= variant for: _assert_scalar(Scalar self, str assert_msg) -> ().
```

Do you know what would be the recommend way to fix that?  Otherwise, the next pin update would fail I think.

**Comment by larryliu0820** [comment]
> @larryliu0820 I'm seeing an ET build failure from PyTorch after [pytorch/pytorch#117378](https://github.com/pytorch/pytorch/pull/117378). The failure is in [pytorch/pytorch#117003](https://github.com/pytorch/pytorch/pull/117003), i.e. https://github.com/pytorch/pytorch/actions/runs/7522657336/job/20474959526#step:5:9155
> 
> ```
> AssertionError: Found an operator that we could not generate an out= variant for: _assert_scalar(Scalar self, str assert_msg) -> ().
> ```
> 
> Do you know what would be the recommend way to fix that? Otherwise, the next pin update would fail I think.

Interesting, this should not be happening because `_assert_scalar` was already added to exclude list (here)[https://github.com/pytorch/pytorch/pull/117378/files#diff-a643946b9b60d3c6d0242c02d1853a8803ede62186defa499e8ed6421e2721feR54]. Can you retry the job?

**Comment by huydhn** [comment]
Oh, you're right. It has been added to the exclude list there, let me try to figure out what why it's still failing.

**Comment by huydhn** [comment]
I think I find the root cause of https://github.com/pytorch/pytorch/pull/117003, let's see if the pinned commit update is fixed by https://github.com/pytorch/pytorch/pull/117518

**Pull request closed without merging**
