### PR TITLE
Revert "Revert "Add full operator to fold dq/q handling" (#7351)"

### PR DESCRIPTION
**Pull request by per**
This reverts commit 11beed1becc76b9ef10f6f8f5268c41cbdcdbfb4.

Re-enable the passes to fold Q/DQ nodes in Arm delegate.

### CODE REVIEW

**Comment by per** [comment]
@digantdesai Added this here to try to sort out the issues with the changes.

**Comment by digantdesai** [comment]
For some reason I can't import it internally ATM :(

**Comment by per** [comment]
Failures due to conda.anaconda.org gives `no healthy upstream`

**Comment by digantdesai** [comment]
@per more type checker gifts for you

```
executorch/backends/arm/_passes/fold_qdq_with_annotated_qparams_pass.py:102:22 Redundant cast [22]: The value being cast is already of type `torch.fx.node.No
```
```
executorch/backends/arm/_passes/fold_qdq_with_annotated_qparams_pass.py:128:42 Incompatible parameter type [6]: In call `torch.fx.node.Node.replace_input_wit
```
```
executorch/backends/arm/operators/op_avg_pool2d.py:11:0 Undefined import [21]: Could not find a module corresponding to import `executorch.backends.arm._pass
```
```
executorch/backends/arm/operators/op_avg_pool2d.py:83:22 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/operators/op_avg_pool2d.py:86:23 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/operators/op_conv2d.py:11:0 Undefined import [21]: Could not find a module corresponding to import `executorch.backends.arm._passes.f
```
```
executorch/backends/arm/operators/op_conv2d.py:167:26 Uninitialized local [61]: Local variable `input_qparams` is undefined, or not always defined.
```
```
executorch/backends/arm/operators/op_conv2d.py:168:27 Uninitialized local [61]: Local variable `input_qparams` is undefined, or not always defined.
```
```
executorch/backends/arm/operators/op_conv2d.py:169:27 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/operators/op_conv2d.py:85:28 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/operators/op_max.py:12:0 Undefined import [21]: Could not find a module corresponding to import `executorch.backends.arm._passes.fold
```
```
executorch/backends/arm/operators/op_max.py:46:28 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/operators/op_min.py:13:0 Undefined import [21]: Could not find a module corresponding to import `executorch.backends.arm._passes.fold
```
```
executorch/backends/arm/operators/op_min.py:47:28 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/process_node.py:115:18 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/process_node.py:14:0 Undefined import [21]: Could not find a module corresponding to import `executorch.backends.arm._passes.fold_qdq
```
```
executorch/backends/arm/tosa_quant_utils.py:114:21 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/tosa_quant_utils.py:60:4 Undefined import [21]: Could not find a module corresponding to import `executorch.backends.arm._passes.fold
```
```
executorch/backends/arm/tosa_quant_utils.py:71:20 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```

**Comment by per** [comment]
Unrelated failure in pull / unittest / macos / macos-job

**Comment by digantdesai** [comment]
Still some more :(
```
executorch/backends/arm/process_node.py:117:18 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/operators/op_conv2d.py:11:0 Undefined import [21]: Could not find a module corresponding to import `executorch.backends.arm._passes.fold_qdq_with_annotated_qparams_pass`.
```
```
executorch/backends/arm/operators/op_max.py:48:28 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```
```
executorch/backends/arm/operators/op_min.py:49:28 Undefined attribute [16]: Module `executorch.backends.arm` has no attribute `_passes`.
```

**Review by digantdesai — COMMENTED** [review]
Thank you @per for all the back and forth.

**Review by digantdesai — APPROVED** [review]

**Review by digantdesai — APPROVED** [review]

**Review by digantdesai — APPROVED** [review]

**Review by digantdesai — APPROVED** [review]

**Pull request merged**
