### PR TITLE
Android App with MediaTek Mode

### PR DESCRIPTION
**Pull request by cmodi-meta**
**Purpose**: Modify the existing demo Android App to support MediaTek e2e flow.

**Pre-requisite**: This diff should sit on top of #6208 changes. We plan to rebase to this once #6208 changes are complete in total.

**Planned Changes**:
 - Backend selector
 - UI Layout
 - Enable to use MTK runner

**How to Run**: 
 1. Compile .aar using https://github.com/pytorch/executorch/pull/6208 . This places .aar in `executorch/examples/demo-apps/android/LlamaDemo`. Make sure to modify the tokenizer, embedding file and model file path in [llama_runner_values.h](https://github.com/pytorch/executorch/pull/6208/files#diff-357e1ebb5046cfd547a196239798d929c26dcba49081aa7d90b5372aa7e69933) before doing so.
 2. Build+launch app using Android Studio for example. (or [alternative](https://github.com/pytorch/executorch/blob/main/examples/demo-apps/android/LlamaDemo/docs/delegates/xnnpack_README.md#run-the-android-demo-app))
 3. In the Setttings widget in the app, select MTK backend and then click Load Model (ensure Llama 3 by default)
 4. After model loads, type "once upon a time". Press enter.
 5. Generated output will appear.

### CODE REVIEW

**Comment by cmodi-meta** [comment]
I've confirmed that the output works (after a bit of hacky change to the if() condition in the `checkForUpdateAndReloadModel()` method). This was required because I initially thought that modelPath and tokenizerPath wouldn't need to be selected but this is not the case. Having paths selected is part of the trigger to load the model.

In order to prevent a one-off, I'll need to make changes to how modelPath and tokenizerPath is selected. Maybe select 1 .pte modelPath or have a json file that contains the paths.

**Comment by cmodi-meta** [comment]
> I've confirmed that the output works (after a bit of hacky change to the if() condition in the `checkForUpdateAndReloadModel()` method). This was required because I initially thought that modelPath and tokenizerPath wouldn't need to be selected but this is not the case. Having paths selected is part of the trigger to load the model.
> 
> In order to prevent a one-off, I'll need to make changes to how modelPath and tokenizerPath is selected. Maybe select 1 .pte modelPath or have a json file that contains the paths.

I've added a temporary placeholder modelPath and tokenizerPath for the MTK backend to support model loading.

**Comment by cmodi-meta** [comment]
Open for review but TODO (once @kirklandsign makes jni changes) is to modify the LlamaModule initialization based on JNI change for how to select MediaTek backend.

**Review by kirklandsign — APPROVED** [review]

**Review by cccclai — APPROVED** [review]
It looks to me that the `mtk_llama_runner` is added by you, and the rest of the changes are mostly related to android, and I'll lean on @kirklandsign to review them. I'll approve and @neuropilot-captain please let us know if you have any concern.

**Comment by cccclai** [comment]
@kirklandsign mentioned the code was mostly borrowed from the runner provided by MediaTek, meaning it's pretty much a fork. The risk is that once the llama runner from mediatek change, this new runner will fail. Let's describe it somewhere in the doc or code

**Pull request merged**
