### PR TITLE
[llava][2/N] Rename llava_encoder to llava

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #4259
* #4256
* #4257
* __->__ #4242
* #4241

Summary: We are planning to support the full llava model so renaming the
directory name.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D59759979](https://our.internmc.facebook.com/intern/diff/D59759979)

### CODE REVIEW

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759979).

**Review by tarun292 — APPROVED** [review]

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759979).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759979).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759979).

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D59759979).

**Pull request closed without merging**
