### PR TITLE
Update PyTorch pinned commit semi-automatically

### PR DESCRIPTION
**Pull request by huydhn**
This setups a nightly job to create a PR to update the pinned PyTorch commit in `.ci/docker/ci_commit_pins/pytorch.txt` and `third-party/pytorch`.  This is still only a semi-automatic process because ET is not yet GHFirst and someone needs to import the PR into fbcode to land it.  Atm, we don't have any automated process to do this or if we even want to implement it because the issue will be resolved once ET become GHFirst.  So, I plan to get this out first before trying to figuring out if there is a work around here.

Note that nightly build of ET will come in a separate PR, which will update how the nightly version on https://github.com/pytorch/executorch/blob/main/install_requirements.sh#L20 is updated.

### Testing

https://github.com/pytorch/executorch/pull/1601.  

The test PR was under my name because I was using my GITHUB_TOKEN there.  Once I use the correct `UPDATEBOT_TOKEN` and `GH_PYTORCHBOT_TOKEN`, they will be used instead like what PyTorch does, i.e. https://github.com/pytorch/pytorch/pull/117003

### CODE REVIEW

**Comment by larryliu0820** [comment]
Does this mean a PR will be created everyday? If so this is a bit spamming I think?

**Comment by huydhn** [comment]
> Does this mean a PR will be created everyday? If so this is a bit spamming I think?

Ah no, if a PR has already been open, it will be reused.  You can see the same behavior on https://github.com/pytorch/pytorch/pull/117003 where the bot tries to update ExecuTorch pinned commit on PyTorch using the same PR.  So there will be at most one open PR at any time.

**Review by larryliu0820 — APPROVED** [review]

**Comment by guangy10** [comment]
@huydhn Sorry for late review. Thanks for implementing this semi-automatic pinned commit update!

> we don't have any automated process to do this or if we even want to implement it because the issue will be resolved once ET become GHFirst.

Agree we should focus on GH1st if working around this requires significant efforts. BTW, since ET is also pinned to PT, it's possible to automatically update pinned ET in PT right?

> Note that nightly build of ET will come in a separate PR, which will update how the nightly version on https://github.com/pytorch/executorch/blob/main/install_requirements.sh#L20 is updated.

Correct me if I missed anything. IIUC ET needs to first have a stable (=viable/strict) branch and a nightly branch which builds off from stable. Once the nightly job is up running, this semi-automatic workflow will pick the latest nightly and update the install_requirements.sh in a single PR.

**Comment by huydhn** [comment]
> Agree we should focus on GH1st if working around this requires significant efforts. BTW, since ET is also pinned to PT, it's possible to automatically update pinned ET in PT right?

The good news is we already have that on PT, for example https://github.com/pytorch/pytorch/pull/117593.  This is fully automated and will be landed once all signals are green.  A couple of things to keep in mind:
* Although they are automated, we still want to pay attention if they are not landed after a few days.  On PT, PT OSS oncalls have that responsibility.
* Increase the coverage of ExecuTorch on PT along the way, not too little but also not too much

>  IIUC ET needs to first have a stable (=viable/strict) branch and a nightly branch which builds off from stable. Once the nightly job is up running, this semi-automatic workflow will pick the latest nightly and update the install_requirements.sh in a single PR.

Yup, that's the idea.  But there might be a tweak if we want a single PR or 2 PRs (1 for pinned commit, 1 for nightly version).  Ideally, I want only 1 PR, but that might need some additional works because the nightly version update is only applicable for ExecuTorch.  So, it won't come from the generic `pytorch/test-infra/.github/actions/update-commit-hash@main` that PT is also using.

**Comment by guangy10** [comment]
> The good news is we already have that on PT, for example https://github.com/pytorch/pytorch/pull/117593. This is fully automated and will be landed once all signals are green.

Great! Just to confirm, today the pinned ET is using the latest commit from main when the job is kicked off. Not the commit of from the stable or nightly since ET doesn't have it yet. We should switch to use stable/nightly commit once avaialbe.

> Ideally, I want only 1 PR, but that might need some additional works because the nightly version update is only applicable for ExecuTorch. So, it won't come from the generic pytorch/test-infra/.github/actions/update-commit-hash@main that PT is also using.

Yeah, 1 PR would be ideal. I think the additional work is to translate the commit hash to the the nightly version? If yes, would it be easier if also using commit hash in install_requirement.sh?

**Comment by huydhn** [comment]
I think going with the main branch is better in practice actually when development work move quickly.  PT pins all vision/audio using main.  As long as we have CI in place, choosing main branch works well.  But switching to stable is also trivial by setting the branch name, i.e. https://github.com/pytorch/executorch/blob/main/.github/workflows/nightly.yml#L28. 

The thing that prevents me from using commit hash in `install_requirement.sh` is that PT will need to be built from source that way.  If my understand is correct, that `install_requirement.sh` script is to allow folks to quickly setup everything they need to use ET locally.  IMO, we could aim at having a similar setup like PyTorch to build everything from source if folks clones from GitHub and provide installation instruction like https://pytorch.org/get-started/locally/ to install nightly ET and all its dependencies (nightly PT, vision, audio, etc).  It's a simple picture.

**Pull request closed without merging**
