### PR TITLE
update doc for phi-3-mini

### PR DESCRIPTION
**Pull request by helunwencser**
Update doc for phi-3-mini to reflect the latest state. Will add a CI job soon to cover this.

Run through instructions in README.md and make sure that everything works.

### CODE REVIEW

**Comment by helunwencser** [comment]
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62597094).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62597182).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62597182).

**Review by tarun292 — APPROVED** [review]

**Review by tarun292 — APPROVED** [review]

**Review by tarun292 — APPROVED** [review]

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62600852).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62600988).

**Comment by helunwencser** [comment]
@helunwencser has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62601117).

**Pull request closed without merging**
