### PR TITLE
Summary: Initial TOSA support in executorch

### PR DESCRIPTION
**Pull request by robell**
An implementation of a TOSA Partitioner and TOSA backend supporting a small list of operators in fp32 and int8/32. This includes a set of integer networks which will then compile to target Ethos-U NPU using the Vela compiler.

* A small set of test networks in fp32
* A subset of these supporting integer and compiling with Vela
* A test wrapper to register and test networks through the compile stack
  * A flow pt2 -> executorch -> tosa_flatbuffer.tosa file -> tosa_reference_model
  * A flow pt2 -> executorch -> tosa_flatbuffer.tosa file -> vela -> command_stream
* This work depends on a few different python modules
  * https://review.mlplatform.org/plugins/gitiles/tosa/serialization_lib/
  * https://review.mlplatform.org/plugins/gitiles/ml/ethos-u/ethos-u-vela/
* This work uses other projects for validation
  * https://review.mlplatform.org/plugins/gitiles/tosa/reference_model/

### CODE REVIEW

**Review by digantdesai — COMMENTED** [review]
Looks good to me. Left some inline comments and some nits. At a high level,

* Let's resolve the testing setup
    * Also the `setup.sh` logic, from the one you shared with me to download, optionally-build, and install deps like `ethos-u-vela`, `serialization_lib` and `reference_model`, can include that with the e2e shell script. So the CI can do the setup and run this e2e. 
    * For these third-party deps, for two git repos and for the one Python pip-package I updated #272 - let me know if you have more questions.

* Besides that, there is an assumption that we have a single delegate which will lower the entire model. I guess OK for now but we should put checks to make sure that is indeed the case

**Review by digantdesai — COMMENTED** [review]
Looks great, getting really close now. Let me know once you resolve the CI issues, and then I think we are good to go from my side :)

**Review by mergennachin — COMMENTED** [review]
Yeah, this is in a good shape to merge. 

Will let @digantdesai to make the call.

@huydhn 

there's a CI failure with this PR: 

https://github.com/pytorch/executorch/actions/runs/6260480754/job/16998596164

In particular, it is having this: 

`error: package directory 'backends/arm/third-party/serialization_lib/python/tosa' does not exist`

Is there anything in the ci infra code that he should change?

**Review by digantdesai — APPROVED** [review]
Looks good to me, DL3 failure seems unrelated. Feel free to merge once DL3 issue is fixed, rebase, just make sure CI is all green.

Thank you @robell!

**Pull request closed without merging**
