### PR TITLE
Arm Backend: Generate input if not supplied in the non semihosting

### PR DESCRIPTION
**Pull request by zingo**
This will generate fake input filled with 1 instead of no input if no input is supplied.

### CODE REVIEW

**Comment by digantdesai** [comment]
sorry I don't see a fill, all I see is a check

**Comment by zingo** [comment]
In the normal case (non semihosting) the check always fails right now, as we don't have any input so the function exits too early by mistake. This check was added when we added the semihosting mode for the FVP to detect if the input file is wrong/missing. E.g. original this function created example input and filled it with 1 (that should be later in the function) but when we added semihosting we missed that we didn't run this code for non semihosting at all.

**Comment by digantdesai** [comment]
I think I get it. In Semihosting mode you don't want to fill 1's for some reason, right?

**Review by digantdesai — APPROVED** [review]

**Comment by robell** [comment]
in semihosting there are files placed with smoketest input/output data so we can compare some more useful tensor input.
This assert was buggy for non-semihosting (run.sh flows) where it early exited the function so we wouldn't get 1's in the tensor, and so e.g. the delegated add would just report 0's instead of 2's.

**Pull request closed without merging**
