### PR TITLE
Fix Arm setup.sh support for Darwin OS

### PR DESCRIPTION
**Pull request by freddan80**
This script needed some changes for Darwin support.

### CODE REVIEW

**Review by digantdesai — APPROVED** [review]
Looks good to me, let me know if you are ok with me merging this

**Comment by freddan80** [comment]
Great! I'm ok with that. Shouldn't it run through some CI tests?

**Comment by freddan80** [comment]
Are the two tests flaky. errors:

https://github.com/pytorch/executorch/actions/runs/7846274854/job/21579259526?pr=1910
https://github.com/pytorch/executorch/actions/runs/7846274854/job/21579259751?pr=1910

seems unrelated. Can I re-run tests?

**Pull request closed without merging**
