### PR TITLE
Qualcomm AI Engine Direct - Enable W2l

### PR DESCRIPTION
**Pull request by winskuo-quic**
Summary:

- Based on the reported issue: https://github.com/pytorch/executorch/issues/1342, there are currently some missing operations when lowering W2l to QNN backend.
- Added log_softmax operation
- Added Conv1D. Since QNN does not support Conv1D, this operation is built using unsqueeze to cast it to Conv2D, and then cast the dimension back during output using squeeze.
- Added Squeeze operation
- Changed node_to_wrappers from [torch.fx.Node, PyQnnWrapper.TensorWrapper] to [str, PyQnnWrapper.TensorWrapper]. It will use node.name as key instead of node because it allows more flexibility in creating extra tensors and nodes for QNN op builders.
- Currently, no scripts are added for W2l as it encountered "No audio backend is available" when using torchaudio. Another PR will be pushed in the future when this this issue can be resolved.

### CODE REVIEW

**Comment by winskuo-quic** [comment]
Hi @kirklandsign,
This PR is used to resolve some of the unsupported OPs in the W2L model, including log_softmax and conv1d.
Please have a look on this PR.
Thanks

**Comment by cccclai** [comment]
Looks nice, thanks! merging

**Comment by cccclai** [comment]
@winskuo-quic will you be able to rebase? Seems like merging fail

**Comment by winskuo-quic** [comment]
> @winskuo-quic will you be able to rebase? Seems like merging fail

Hi @cccclai,
Thanks for reviewing the PR and the friendly reminder.
I will push a new commit once the conflicts are resolved and unit tests are passing.

**Pull request closed without merging**
