### PR TITLE
Add configuration file for compiler

### PR DESCRIPTION
**Pull request by per**
Add a default config.ini for the vela compiler to pick up to be able to set system config and memory mode.

Change-Id: I5369675f81c4d8e9b3f71ec5e67c5bf4bf4cf433

### CODE REVIEW

**Review by digantdesai — APPROVED** [review]
LGTM

**Review by mergennachin — APPROVED** [review]

**Comment by digantdesai** [comment]
> https://github.com/pytorch/executorch/actions/runs/8184884923/job/22380154215?pr=2292#logs

Is this a compiler issue for the CI job?

**Comment by digantdesai** [comment]
Rebase on top of the fix 2294?

**Comment by per** [comment]
> Rebase on top of the fix 2294?

Sure, will do. The failing CI test was not related to this change.

**Comment by digantdesai** [comment]
Apologies, can we rebase this please?

**Comment by per** [comment]
> Apologies, can we rebase this please?

Done!

**Comment by digantdesai** [comment]
Seems like unrelated failures, let me "bypass" these and try to merge.

**Pull request closed without merging**
