### PR TITLE
Create dependabot rule to upgrade TorchFix version

### PR DESCRIPTION
**Pull request by huydhn**
The parameters are from From https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

### Testing
On my own fork https://github.com/huydhn/executorch/blob/main/.github/dependabot.yml, and the PR to upgrade TorchFix is created successfully https://github.com/huydhn/executorch/pull/2

### CODE REVIEW

**Comment by kit1980** [comment]
Why not just unpin?

**Comment by huydhn** [comment]
> Why not just unpin?

Like PT, ET is currently pinned all their dependencies as part of Docker image build, so I think having a PR like https://github.com/huydhn/executorch/pull/2 would allow ET owner to control the upgrade process and land the PR only when it looks good.

**Comment by huydhn** [comment]
I switch the reviewer to `pytorch/team-executorch` as they are the owners.

**Comment by kit1980** [comment]
There is a chance that new TorchFix release will introduce CI failures after new rules added to TorchFix.
I wonder how this going to be handled in the dependabot workflow.

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
