### PR TITLE
Inspector APIs page

### PR DESCRIPTION
**Pull request by Olivia-liu**
Differential Revision: D56447799

### CODE REVIEW

**Review by mikekgfb — APPROVED** [review]

**Comment by huydhn** [comment]
I think the cherry pick bot fails on this PR because it wasn't merged properly by the bot, i.e. https://github.com/pytorch/executorch/pull/3260#issuecomment-2073792645.  Here is the corresponding log https://github.com/pytorch/executorch/actions/runs/8822987799/job/24222413111, so I think this will need to be cherry pick manually.

**Pull request closed without merging**
